from __future__ import annotations

import fnmatch
import json
from collections import Counter
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Mapping

from .ledger_models import to_jsonable
from .ledger_policy import CountVerdict, classify_path
from .source_extraction import DEFAULT_EXCLUDE_PATTERNS, SOURCE_SUFFIXES, ExtractionPlan, normalize_repo_path


class RuleDecision(StrEnum):
    INCLUDE = "include"
    EXCLUDE = "exclude"
    BLOCK = "block"
    REVIEW = "review"


class RuleReason(StrEnum):
    INCLUDED_BY_EXPLICIT_PATH = "included_by_explicit_path"
    INCLUDED_BY_PROFILE = "included_by_profile"
    EXCLUDED_BY_PATTERN = "excluded_by_pattern"
    EXCLUDED_BY_SUFFIX = "excluded_by_suffix"
    EXCLUDED_BY_CONTENT = "excluded_by_content"
    BLOCKED_PARENT_REFERENCE = "blocked_parent_reference"
    BLOCKED_ABSOLUTE_PATH = "blocked_absolute_path"
    BLOCKED_TARGET_ESCAPE = "blocked_target_escape"
    BLOCKED_SOURCE_ESCAPE = "blocked_source_escape"
    REVIEW_VENDOR_RUNTIME = "review_vendor_runtime"
    REVIEW_UNKNOWN_SOURCE = "review_unknown_source"


class SourceProfileKind(StrEnum):
    CODE_RUNTIME = "code_runtime"
    BROWSER_RUNTIME = "browser_runtime"
    APP_SERVER = "app_server"
    WORKFLOW_RUNTIME = "workflow_runtime"
    MEMORY_RUNTIME = "memory_runtime"
    REFERENCE_ONLY = "reference_only"


class RuleCoverageSeverity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    BLOCKER = "blocker"


class RuleCoverageCode(StrEnum):
    CAPABILITY_UNMAPPED = "capability_unmapped"
    INCLUDE_HAS_NO_MATERIALIZED_SOURCE = "include_has_no_materialized_source"
    INCLUDED_FILE_IS_NOT_COUNTABLE = "included_file_is_not_countable"
    REVIEW_FILE_UNOWNED = "review_file_unowned"
    EXCLUSION_DID_NOT_MATCH = "exclusion_did_not_match"
    PILOT_WIDTH_OUT_OF_RANGE = "pilot_width_out_of_range"
    SOURCE_SUFFIX_UNCLASSIFIED = "source_suffix_unclassified"


@dataclass(frozen=True, slots=True)
class PatternRule:
    pattern: str
    reason: str
    decision: RuleDecision = RuleDecision.EXCLUDE
    inherited: bool = False

    def matches(self, repo_path: str) -> bool:
        normalized = normalize_repo_path(self.pattern)
        if fnmatch.fnmatch(repo_path, normalized):
            return True
        if normalized.startswith("**/") and fnmatch.fnmatch(repo_path, normalized[3:]):
            return True
        if normalized.endswith("/**"):
            prefix = normalized[:-3]
            return repo_path == prefix or repo_path.startswith(prefix + "/")
        return False

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(frozen=True, slots=True)
class IncludeRule:
    path: str
    owner_unit: str
    downstream_units: tuple[str, ...]
    capability: str
    reason: str
    recursive: bool = True

    def matches(self, repo_path: str) -> bool:
        normalized = normalize_repo_path(self.path)
        if repo_path == normalized:
            return True
        return self.recursive and repo_path.startswith(normalized.rstrip("/") + "/")

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(frozen=True, slots=True)
class ExtractionRuleProfile:
    source_repo: str
    kind: SourceProfileKind
    includes: tuple[IncludeRule, ...]
    excludes: tuple[PatternRule, ...] = field(default_factory=tuple)
    source_suffixes: tuple[str, ...] = tuple(sorted(SOURCE_SUFFIXES))
    content_markers_excluded: tuple[str, ...] = (
        "Auto-generated type stub",
        "Generated by",
        "DO NOT EDIT",
    )
    min_pilot_files: int = 1
    max_pilot_files: int = 250
    notes: tuple[str, ...] = field(default_factory=tuple)

    def all_excludes(self) -> tuple[PatternRule, ...]:
        inherited = tuple(
            PatternRule(pattern=pattern, reason="default extraction exclusion", inherited=True)
            for pattern in DEFAULT_EXCLUDE_PATTERNS
        )
        return (*inherited, *self.excludes)

    def include_for(self, repo_path: str) -> IncludeRule | None:
        for include in self.includes:
            if include.matches(repo_path):
                return include
        return None

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(frozen=True, slots=True)
class RuleEvaluation:
    source_repo: str
    repo_path: str
    decision: RuleDecision
    reason: RuleReason
    message: str
    include_rule: IncludeRule | None = None
    exclude_rule: PatternRule | None = None
    suffix: str = ""
    content_marker: str = ""
    target_path: str = ""
    target_verdict: str = ""

    @property
    def countable(self) -> bool:
        return self.decision == RuleDecision.INCLUDE and self.target_verdict == str(CountVerdict.EFFECTIVE)

    def to_dict(self) -> dict[str, Any]:
        payload = to_jsonable(self)
        payload["countable"] = self.countable
        return payload


@dataclass(frozen=True, slots=True)
class RuleFinding:
    code: str
    severity: str
    message: str
    path: str = ""
    remediation: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(slots=True)
class SourceTreeMetrics:
    source_repo: str
    source_root: str
    scanned_files: int = 0
    included_files: int = 0
    excluded_files: int = 0
    blocked_files: int = 0
    review_files: int = 0
    source_like_files: int = 0
    source_like_lines: int = 0
    excluded_lines: int = 0
    blocked_lines: int = 0
    missing_include_paths: list[str] = field(default_factory=list)
    suffix_counts: dict[str, int] = field(default_factory=dict)

    def record(self, evaluation: RuleEvaluation, line_count: int) -> None:
        self.scanned_files += 1
        suffix = evaluation.suffix or "<none>"
        self.suffix_counts[suffix] = self.suffix_counts.get(suffix, 0) + 1
        if evaluation.decision == RuleDecision.INCLUDE:
            self.included_files += 1
            self.source_like_files += 1
            self.source_like_lines += line_count
        elif evaluation.decision == RuleDecision.EXCLUDE:
            self.excluded_files += 1
            self.excluded_lines += line_count
        elif evaluation.decision == RuleDecision.BLOCK:
            self.blocked_files += 1
            self.blocked_lines += line_count
        else:
            self.review_files += 1

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(slots=True)
class ExtractionRuleAudit:
    profile: ExtractionRuleProfile
    source_root: Path
    target_root: Path
    evaluations: list[RuleEvaluation] = field(default_factory=list)
    findings: list[RuleFinding] = field(default_factory=list)
    metrics: SourceTreeMetrics | None = None

    @property
    def ok(self) -> bool:
        return not any(finding.severity in {"error", "blocker"} for finding in self.findings)

    @property
    def include_paths(self) -> list[str]:
        return sorted(evaluation.repo_path for evaluation in self.evaluations if evaluation.decision == RuleDecision.INCLUDE)

    @property
    def blocked_paths(self) -> list[str]:
        return sorted(evaluation.repo_path for evaluation in self.evaluations if evaluation.decision == RuleDecision.BLOCK)

    @property
    def excluded_paths(self) -> list[str]:
        return sorted(evaluation.repo_path for evaluation in self.evaluations if evaluation.decision == RuleDecision.EXCLUDE)

    def summary(self) -> dict[str, Any]:
        metrics = self.metrics or SourceTreeMetrics(self.profile.source_repo, str(self.source_root))
        return {
            "ok": self.ok,
            "source_repo": self.profile.source_repo,
            "source_root": str(self.source_root),
            "target_root": str(self.target_root),
            "profile_kind": str(self.profile.kind),
            "scanned_files": metrics.scanned_files,
            "included_files": metrics.included_files,
            "excluded_files": metrics.excluded_files,
            "blocked_files": metrics.blocked_files,
            "review_files": metrics.review_files,
            "source_like_lines": metrics.source_like_lines,
            "excluded_lines": metrics.excluded_lines,
            "blocked_lines": metrics.blocked_lines,
            "finding_count": len(self.findings),
            "error_count": sum(1 for item in self.findings if item.severity == "error"),
            "blocker_count": sum(1 for item in self.findings if item.severity == "blocker"),
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "summary": self.summary(),
            "profile": self.profile.to_dict(),
            "metrics": self.metrics.to_dict() if self.metrics else {},
            "findings": [finding.to_dict() for finding in self.findings],
            "evaluations": [evaluation.to_dict() for evaluation in self.evaluations],
        }


@dataclass(frozen=True, slots=True)
class IncludeCoverageRow:
    include_path: str
    owner_unit: str
    downstream_units: tuple[str, ...]
    capability: str
    included_files: int = 0
    excluded_files: int = 0
    review_files: int = 0
    blocked_files: int = 0
    source_like_lines: int = 0
    suffix_counts: dict[str, int] = field(default_factory=dict)

    @property
    def has_materialized_source(self) -> bool:
        return self.included_files > 0

    @property
    def ok(self) -> bool:
        return self.blocked_files == 0 and self.has_materialized_source

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(frozen=True, slots=True)
class RuleCoverageFinding:
    code: RuleCoverageCode
    severity: RuleCoverageSeverity
    message: str
    include_path: str = ""
    repo_path: str = ""
    remediation: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(self)


@dataclass(slots=True)
class RuleCoverageReport:
    source_repo: str
    profile_kind: SourceProfileKind
    rows: list[IncludeCoverageRow]
    findings: list[RuleCoverageFinding]
    suffix_counts: dict[str, int]
    decision_counts: dict[str, int]
    summary: dict[str, Any]

    @property
    def ok(self) -> bool:
        return not any(finding.severity in {RuleCoverageSeverity.ERROR, RuleCoverageSeverity.BLOCKER} for finding in self.findings)

    def by_capability(self) -> dict[str, IncludeCoverageRow]:
        return {row.capability: row for row in self.rows}

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "source_repo": self.source_repo,
            "profile_kind": str(self.profile_kind),
            "rows": [row.to_dict() for row in self.rows],
            "findings": [finding.to_dict() for finding in self.findings],
            "suffix_counts": dict(sorted(self.suffix_counts.items())),
            "decision_counts": dict(sorted(self.decision_counts.items())),
            "summary": dict(self.summary),
        }


def build_rule_coverage_report(audit: ExtractionRuleAudit) -> RuleCoverageReport:
    row_builders: dict[str, dict[str, Any]] = {}
    for include in audit.profile.includes:
        row_builders[normalize_repo_path(include.path)] = {
            "include_path": normalize_repo_path(include.path),
            "owner_unit": include.owner_unit,
            "downstream_units": include.downstream_units,
            "capability": include.capability,
            "included_files": 0,
            "excluded_files": 0,
            "review_files": 0,
            "blocked_files": 0,
            "source_like_lines": 0,
            "suffix_counts": Counter(),
        }

    suffix_counts: Counter[str] = Counter()
    decision_counts: Counter[str] = Counter()
    findings: list[RuleCoverageFinding] = []
    seen_excludes: Counter[str] = Counter()
    source_root = audit.source_root.resolve()
    target_is_source_pool = "vendor-runtimes" in audit.target_root.as_posix().split("/")

    for evaluation in audit.evaluations:
        suffix_counts[evaluation.suffix or "<none>"] += 1
        decision_counts[str(evaluation.decision)] += 1
        if evaluation.exclude_rule is not None:
            seen_excludes[evaluation.exclude_rule.pattern] += 1
        if evaluation.include_rule is None:
            if evaluation.decision == RuleDecision.REVIEW:
                findings.append(
                    RuleCoverageFinding(
                        code=RuleCoverageCode.REVIEW_FILE_UNOWNED,
                        severity=RuleCoverageSeverity.WARNING,
                        message="candidate file was not owned by any include rule",
                        repo_path=evaluation.repo_path,
                        remediation="Add an explicit include rule or keep it outside the pilot extraction.",
                    )
                )
            continue
        key = normalize_repo_path(evaluation.include_rule.path)
        row = row_builders.setdefault(
            key,
            {
                "include_path": key,
                "owner_unit": evaluation.include_rule.owner_unit,
                "downstream_units": evaluation.include_rule.downstream_units,
                "capability": evaluation.include_rule.capability,
                "included_files": 0,
                "excluded_files": 0,
                "review_files": 0,
                "blocked_files": 0,
                "source_like_lines": 0,
                "suffix_counts": Counter(),
            },
        )
        row["suffix_counts"][evaluation.suffix or "<none>"] += 1
        if evaluation.decision == RuleDecision.INCLUDE:
            row["included_files"] += 1
            row["source_like_lines"] += _line_count(source_root / evaluation.repo_path)
            if (
                evaluation.target_verdict
                and evaluation.target_verdict != str(CountVerdict.EFFECTIVE)
                and not target_is_source_pool
            ):
                findings.append(
                    RuleCoverageFinding(
                        code=RuleCoverageCode.INCLUDED_FILE_IS_NOT_COUNTABLE,
                        severity=RuleCoverageSeverity.ERROR,
                        message="included file maps to a target path that is not countable source",
                        include_path=key,
                        repo_path=evaluation.repo_path,
                        remediation="Route source-pool copies through ledger bindings and keep effective Zyra modules separate.",
                        metadata={"target_path": evaluation.target_path, "target_verdict": evaluation.target_verdict},
                    )
                )
        elif evaluation.decision == RuleDecision.EXCLUDE:
            row["excluded_files"] += 1
        elif evaluation.decision == RuleDecision.REVIEW:
            row["review_files"] += 1
        else:
            row["blocked_files"] += 1

    rows: list[IncludeCoverageRow] = []
    for include in audit.profile.includes:
        key = normalize_repo_path(include.path)
        item = row_builders[key]
        rows.append(
            IncludeCoverageRow(
                include_path=item["include_path"],
                owner_unit=item["owner_unit"],
                downstream_units=tuple(item["downstream_units"]),
                capability=item["capability"],
                included_files=int(item["included_files"]),
                excluded_files=int(item["excluded_files"]),
                review_files=int(item["review_files"]),
                blocked_files=int(item["blocked_files"]),
                source_like_lines=int(item["source_like_lines"]),
                suffix_counts=dict(sorted(item["suffix_counts"].items())),
            )
        )

    for row in rows:
        if not row.has_materialized_source:
            findings.append(
                RuleCoverageFinding(
                    code=RuleCoverageCode.INCLUDE_HAS_NO_MATERIALIZED_SOURCE,
                    severity=RuleCoverageSeverity.ERROR,
                    message=f"include rule {row.include_path} did not materialize any source file",
                    include_path=row.include_path,
                    remediation="Refresh the include rule or defer this capability to the owning execution unit.",
                    metadata={"capability": row.capability, "downstream_units": list(row.downstream_units)},
                )
            )
        if not row.capability.strip():
            findings.append(
                RuleCoverageFinding(
                    code=RuleCoverageCode.CAPABILITY_UNMAPPED,
                    severity=RuleCoverageSeverity.ERROR,
                    message="include rule has no capability label",
                    include_path=row.include_path,
                    remediation="Name the runtime capability so ledger entries can explain source-to-target intent.",
                )
            )

    if audit.metrics:
        included = audit.metrics.included_files
        if included < audit.profile.min_pilot_files or included > audit.profile.max_pilot_files:
            findings.append(
                RuleCoverageFinding(
                    code=RuleCoverageCode.PILOT_WIDTH_OUT_OF_RANGE,
                    severity=RuleCoverageSeverity.ERROR,
                    message="pilot extraction width is outside profile bounds",
                    remediation="Keep the pilot narrow but large enough to prove the migration path.",
                    metadata={
                        "included_files": included,
                        "min_pilot_files": audit.profile.min_pilot_files,
                        "max_pilot_files": audit.profile.max_pilot_files,
                    },
                )
            )

    for exclude in audit.profile.excludes:
        if seen_excludes[exclude.pattern] == 0 and not exclude.inherited:
            findings.append(
                RuleCoverageFinding(
                    code=RuleCoverageCode.EXCLUSION_DID_NOT_MATCH,
                    severity=RuleCoverageSeverity.INFO,
                    message="profile exclusion did not match the current pilot tree",
                    remediation="Keep defensive exclusions if the downstream unit may expand the include path.",
                    metadata={"pattern": exclude.pattern, "reason": exclude.reason},
                )
            )

    for suffix, count in suffix_counts.items():
        if suffix not in audit.profile.source_suffixes and suffix != "<none>":
            findings.append(
                RuleCoverageFinding(
                    code=RuleCoverageCode.SOURCE_SUFFIX_UNCLASSIFIED,
                    severity=RuleCoverageSeverity.WARNING,
                    message=f"candidate suffix {suffix} is outside the source suffix allowlist",
                    remediation="Confirm the suffix should stay excluded or extend SOURCE_SUFFIXES with a test.",
                    metadata={"suffix": suffix, "count": count},
                )
            )

    blocking = sum(1 for finding in findings if finding.severity in {RuleCoverageSeverity.ERROR, RuleCoverageSeverity.BLOCKER})
    summary = {
        "ok": blocking == 0,
        "include_rule_count": len(rows),
        "covered_include_rule_count": sum(1 for row in rows if row.has_materialized_source),
        "included_files": audit.summary()["included_files"],
        "source_like_lines": audit.summary()["source_like_lines"],
        "finding_count": len(findings),
        "blocking_findings": blocking,
        "decision_counts": dict(sorted(decision_counts.items())),
        "suffix_counts": dict(sorted(suffix_counts.items())),
    }
    return RuleCoverageReport(
        source_repo=audit.profile.source_repo,
        profile_kind=audit.profile.kind,
        rows=rows,
        findings=findings,
        suffix_counts=dict(suffix_counts),
        decision_counts=dict(decision_counts),
        summary=summary,
    )


class ExtractionRuleEngine:
    def __init__(self, profile: ExtractionRuleProfile) -> None:
        self.profile = profile

    def evaluate_path(
        self,
        repo_path: str,
        *,
        source_root: Path | None = None,
        target_root: Path | None = None,
        target_mount: str = "",
    ) -> RuleEvaluation:
        normalized = normalize_repo_path(repo_path)
        suffix = PurePosixPath(normalized).suffix.lower()
        if _has_parent_reference(normalized):
            return RuleEvaluation(
                source_repo=self.profile.source_repo,
                repo_path=normalized,
                decision=RuleDecision.BLOCK,
                reason=RuleReason.BLOCKED_PARENT_REFERENCE,
                message="source path contains parent traversal",
                suffix=suffix,
            )
        if _is_absolute_like(normalized):
            return RuleEvaluation(
                source_repo=self.profile.source_repo,
                repo_path=normalized,
                decision=RuleDecision.BLOCK,
                reason=RuleReason.BLOCKED_ABSOLUTE_PATH,
                message="source path must be repository-relative",
                suffix=suffix,
            )
        include = self.profile.include_for(normalized)
        if include is None:
            return RuleEvaluation(
                source_repo=self.profile.source_repo,
                repo_path=normalized,
                decision=RuleDecision.REVIEW,
                reason=RuleReason.REVIEW_UNKNOWN_SOURCE,
                message="path is not matched by any include rule",
                suffix=suffix,
            )
        for exclude in self.profile.all_excludes():
            if exclude.matches(normalized):
                return RuleEvaluation(
                    source_repo=self.profile.source_repo,
                    repo_path=normalized,
                    decision=RuleDecision.EXCLUDE,
                    reason=RuleReason.EXCLUDED_BY_PATTERN,
                    message=exclude.reason,
                    include_rule=include,
                    exclude_rule=exclude,
                    suffix=suffix,
                )
        if suffix not in self.profile.source_suffixes:
            return RuleEvaluation(
                source_repo=self.profile.source_repo,
                repo_path=normalized,
                decision=RuleDecision.EXCLUDE,
                reason=RuleReason.EXCLUDED_BY_SUFFIX,
                message=f"suffix {suffix or '<none>'} is not treated as runtime source",
                include_rule=include,
                suffix=suffix,
            )
        marker = ""
        if source_root is not None:
            source_path = (source_root / normalized).resolve()
            try:
                source_path.relative_to(source_root.resolve())
            except ValueError:
                return RuleEvaluation(
                    source_repo=self.profile.source_repo,
                    repo_path=normalized,
                    decision=RuleDecision.BLOCK,
                    reason=RuleReason.BLOCKED_SOURCE_ESCAPE,
                    message="resolved source path escapes source root",
                    include_rule=include,
                    suffix=suffix,
                )
            marker = _matched_content_marker(source_path, self.profile.content_markers_excluded)
            if marker:
                return RuleEvaluation(
                    source_repo=self.profile.source_repo,
                    repo_path=normalized,
                    decision=RuleDecision.EXCLUDE,
                    reason=RuleReason.EXCLUDED_BY_CONTENT,
                    message=f"content marker is excluded: {marker}",
                    include_rule=include,
                    suffix=suffix,
                    content_marker=marker,
                )
        target_path = ""
        target_verdict = ""
        if target_root is not None:
            mount = normalize_repo_path(target_mount).strip("/")
            target_relative = f"{mount}/{normalized}" if mount else normalized
            candidate = (target_root / target_relative).resolve()
            try:
                candidate.relative_to(target_root.resolve())
            except ValueError:
                return RuleEvaluation(
                    source_repo=self.profile.source_repo,
                    repo_path=normalized,
                    decision=RuleDecision.BLOCK,
                    reason=RuleReason.BLOCKED_TARGET_ESCAPE,
                    message="resolved target path escapes target root",
                    include_rule=include,
                    suffix=suffix,
                )
            target_path = target_relative
            target_verdict = str(classify_path(target_relative).verdict)
        return RuleEvaluation(
            source_repo=self.profile.source_repo,
            repo_path=normalized,
            decision=RuleDecision.INCLUDE,
            reason=RuleReason.INCLUDED_BY_PROFILE,
            message=include.reason,
            include_rule=include,
            suffix=suffix,
            content_marker=marker,
            target_path=target_path,
            target_verdict=target_verdict,
        )

    def audit_plan(self, plan: ExtractionPlan) -> ExtractionRuleAudit:
        source_root = plan.source_root.resolve()
        target_root = plan.normalized_target_root()
        metrics = SourceTreeMetrics(self.profile.source_repo, str(source_root))
        findings: list[RuleFinding] = []
        evaluations: list[RuleEvaluation] = []
        if plan.source_repo != self.profile.source_repo:
            findings.append(
                RuleFinding(
                    code="SOURCE_REPO_PROFILE_MISMATCH",
                    severity="error",
                    message=f"plan source_repo={plan.source_repo} does not match profile {self.profile.source_repo}",
                    remediation="Use the repository-specific extraction profile.",
                )
            )
        if not source_root.exists():
            findings.append(
                RuleFinding(
                    code="SOURCE_ROOT_MISSING",
                    severity="blocker",
                    message=f"source root does not exist: {source_root}",
                    remediation="Run extraction only from a checked out source repository.",
                )
            )
        for include in plan.include_paths:
            include_path = source_root / normalize_repo_path(include)
            if not include_path.exists():
                metrics.missing_include_paths.append(normalize_repo_path(include))
        for repo_path in _iter_plan_candidate_paths(plan):
            evaluation = self.evaluate_path(
                repo_path,
                source_root=source_root,
                target_root=target_root,
                target_mount=plan.target_mount,
            )
            line_count = _line_count(source_root / normalize_repo_path(repo_path))
            metrics.record(evaluation, line_count)
            evaluations.append(evaluation)
            if evaluation.decision == RuleDecision.BLOCK:
                findings.append(
                    RuleFinding(
                        code="BLOCKED_EXTRACTION_PATH",
                        severity="blocker",
                        message=evaluation.message,
                        path=evaluation.repo_path,
                        remediation="Remove parent/absolute/escaping paths from include rules.",
                        metadata=evaluation.to_dict(),
                    )
                )
        if metrics.missing_include_paths:
            findings.append(
                RuleFinding(
                    code="INCLUDE_PATH_MISSING",
                    severity="error",
                    message=f"{len(metrics.missing_include_paths)} include path(s) do not exist",
                    remediation="Refresh the source profile or defer the missing source item with a ledger reason.",
                    metadata={"missing_include_paths": list(metrics.missing_include_paths)},
                )
            )
        if metrics.included_files < self.profile.min_pilot_files:
            findings.append(
                RuleFinding(
                    code="PILOT_TOO_SMALL",
                    severity="error",
                    message=f"profile requires at least {self.profile.min_pilot_files} included files",
                    remediation="Select enough source files to prove the extraction path without claiming full productization.",
                    metadata={"included_files": metrics.included_files},
                )
            )
        if metrics.included_files > self.profile.max_pilot_files and plan.owner_unit == "M1-01B":
            findings.append(
                RuleFinding(
                    code="PILOT_TOO_BROAD",
                    severity="warning",
                    message=f"M1-01B pilot includes {metrics.included_files} files; this may look like a source pool.",
                    remediation="Keep M1-01B pilot narrow and leave full productization to M1-02A.",
                    metadata={"included_files": metrics.included_files, "max_pilot_files": self.profile.max_pilot_files},
                )
            )
        return ExtractionRuleAudit(
            profile=self.profile,
            source_root=source_root,
            target_root=target_root,
            evaluations=evaluations,
            findings=findings,
            metrics=metrics,
        )


def default_extraction_profiles() -> dict[str, ExtractionRuleProfile]:
    return {
        "claude-code-best": claude_code_runtime_profile(),
        "browser-use": browser_use_runtime_profile(),
        "OpenHands": openhands_app_server_profile(),
    }


def claude_code_runtime_profile() -> ExtractionRuleProfile:
    return ExtractionRuleProfile(
        source_repo="claude-code-best",
        kind=SourceProfileKind.CODE_RUNTIME,
        min_pilot_files=20,
        max_pilot_files=80,
        includes=(
            IncludeRule("src/Tool.ts", "M1-01B", ("M1-02A", "M1-02C"), "tool contract", "core Tool contract"),
            IncludeRule("src/tools.ts", "M1-01B", ("M1-02A", "M1-02C"), "tool registry", "base tool registry"),
            IncludeRule("src/query", "M1-01B", ("M1-02A", "M1-02B"), "query loop support", "query support folder"),
            IncludeRule("src/services/tools", "M1-01B", ("M1-02C",), "tool orchestration", "tool execution services"),
            IncludeRule("src/tools/BashTool", "M1-01B", ("M1-02C", "M1-03A"), "shell permission", "bash tool contracts"),
            IncludeRule("src/tools/AgentTool", "M1-01B", ("M1-03D",), "subagent contract", "AgentTool support"),
            IncludeRule("src/tools/SkillTool", "M1-01B", ("M1-03C",), "skill contract", "SkillTool support"),
            IncludeRule("src/types", "M1-01B", ("M1-02A",), "runtime types", "selected type contracts"),
            IncludeRule("src/utils/sessionState.ts", "M1-01B", ("M1-02B",), "session state", "session state helper", recursive=False),
            IncludeRule("src/context.ts", "M1-01B", ("M1-02D",), "context contract", "context builder", recursive=False),
            IncludeRule("src/cost-tracker.ts", "M1-01B", ("M1-02C",), "cost budget", "usage tracking", recursive=False),
        ),
        excludes=(
            PatternRule("src/**/__tests__/**", "upstream tests are not part of pilot runtime"),
            PatternRule("src/**/*.snap", "snapshots are fixture-like"),
            PatternRule("src/**/fixtures/**", "fixtures are excluded"),
            PatternRule("src/**/*.d.ts", "type stubs are excluded unless explicitly ported"),
            PatternRule("src/entrypoints/**", "product brand entrypoints are excluded"),
            PatternRule("src/components/**", "TUI/React presentation is not M1-01B runtime scaffold"),
        ),
        notes=(
            "M1-01B pilot must remain a narrow proof of extraction; M1-02A owns productized QueryEngine migration.",
            "Vendor runtime source lines are source-pool scale and not strict effective line count.",
        ),
    )


def browser_use_runtime_profile() -> ExtractionRuleProfile:
    return ExtractionRuleProfile(
        source_repo="browser-use",
        kind=SourceProfileKind.BROWSER_RUNTIME,
        min_pilot_files=3,
        max_pilot_files=60,
        includes=(
            IncludeRule("browser_use/agent/message_manager", "M1-04B", ("M1-04D",), "message compression", "browser message manager"),
            IncludeRule("browser_use/tools/registry", "M1-04C", ("M1-04D",), "action registry", "browser action registry"),
            IncludeRule("browser_use/browser/watchdogs", "M1-04D", ("M1-07B",), "watchdog", "browser watchdogs"),
            IncludeRule("browser_use/browser/session.py", "M1-04A", ("M1-04B",), "browser session", "browser session service", recursive=False),
        ),
        excludes=(
            PatternRule("**/examples/**", "examples are not productized runtime"),
            PatternRule("**/tests/**", "upstream tests are not migrated as runtime"),
            PatternRule("**/docs/**", "documentation is reference-only"),
        ),
    )


def openhands_app_server_profile() -> ExtractionRuleProfile:
    return ExtractionRuleProfile(
        source_repo="OpenHands",
        kind=SourceProfileKind.APP_SERVER,
        min_pilot_files=3,
        max_pilot_files=80,
        includes=(
            IncludeRule("openhands/app_server/event", "M1-05C", ("M2-01B",), "event service", "event service boundary"),
            IncludeRule("openhands/app_server/app_conversation", "M1-05D", ("M2-01A",), "conversation lifecycle", "conversation service"),
            IncludeRule("openhands/app_server/file_store", "M1-05A", ("M2-03A",), "artifact store", "file/artifact store"),
        ),
        excludes=(
            PatternRule("frontend/**", "frontend is not an M1 backend runtime extraction"),
            PatternRule("**/tests/**", "upstream tests are not runtime productization"),
            PatternRule("**/docs/**", "documentation is reference-only"),
        ),
    )


def profile_for_plan(plan: ExtractionPlan) -> ExtractionRuleProfile:
    profiles = default_extraction_profiles()
    return profiles.get(
        plan.source_repo,
        ExtractionRuleProfile(
            source_repo=plan.source_repo,
            kind=SourceProfileKind.WORKFLOW_RUNTIME,
            includes=tuple(
                IncludeRule(path, plan.owner_unit, tuple(plan.downstream_units), "explicit include", "explicit plan include")
                for path in plan.include_paths
            ),
            min_pilot_files=1,
            max_pilot_files=250,
        ),
    )


def audit_extraction_plan(plan: ExtractionPlan) -> ExtractionRuleAudit:
    return ExtractionRuleEngine(profile_for_plan(plan)).audit_plan(plan)


def build_rule_report_for_plan(plan: ExtractionPlan) -> dict[str, Any]:
    return audit_extraction_plan(plan).to_dict()


def write_rule_report_for_plan(plan: ExtractionPlan, output_path: str | Path) -> Path:
    report = build_rule_report_for_plan(plan)
    path = Path(output_path)
    if not path.is_absolute():
        path = plan.project_root / path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _iter_plan_candidate_paths(plan: ExtractionPlan) -> list[str]:
    source_root = plan.source_root.resolve()
    candidates: set[str] = set()
    for include in plan.include_paths:
        normalized = normalize_repo_path(include)
        source_path = source_root / normalized
        if source_path.is_file():
            candidates.add(normalized)
        elif source_path.is_dir():
            for child in source_path.rglob("*"):
                if child.is_file():
                    candidates.add(child.relative_to(source_root).as_posix())
        else:
            candidates.add(normalized)
    return sorted(candidates)


def _line_count(path: Path) -> int:
    if not path.exists() or not path.is_file():
        return 0
    try:
        return len(path.read_text(encoding="utf-8", errors="replace").splitlines())
    except OSError:
        return 0


def _matched_content_marker(path: Path, markers: Iterable[str]) -> str:
    if not path.exists() or not path.is_file():
        return ""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    for marker in markers:
        if marker and marker in text:
            return marker
    return ""


def _has_parent_reference(path: str) -> bool:
    return ".." in PurePosixPath(path).parts


def _is_absolute_like(path: str) -> bool:
    parts = PurePosixPath(path).parts
    return path.startswith("/") or bool(parts and ":" in parts[0])
