from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import tomllib
import zipfile
from collections.abc import Mapping, Sequence
from pathlib import Path, PurePosixPath
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
INTEGRATIONS_ROOT = PROJECT_ROOT / "packages" / "integrations"
if str(INTEGRATIONS_ROOT) not in sys.path:
    sys.path.insert(0, str(INTEGRATIONS_ROOT))

from zyra_integrations.loopx.runtime.manifest import (
    LOOPX_SOURCE_COMMIT,
    LOOPX_SOURCE_REF,
    LOOPX_SOURCE_TREE_COMMIT,
    LOOPX_VERSION,
    PACKAGE_LOCK_SCHEMA,
    SOURCE_MANIFEST_NAME,
    SOURCE_MANIFEST_SCHEMA,
    sha256_file,
    source_manifest_digest,
    stable_digest,
)


EMBEDDED_ROOT = (
    PROJECT_ROOT / "packages" / "integrations" / "loopx_runtime"
)
LOCK_PATH = PROJECT_ROOT / "config" / "loopx" / "package-lock.json"
PACKAGED_METADATA_ROOT = (
    PROJECT_ROOT
    / "packages"
    / "integrations"
    / "zyra_integrations"
    / "loopx"
    / "runtime"
)
EXCLUSIONS = (
    {
        "pattern": ".git/**",
        "reason": "Git object database and worktree metadata are not release runtime inputs.",
    },
    {
        "pattern": ".github/**",
        "reason": "Upstream CI and issue automation do not participate in import, CLI, extension, resource, or tests.",
    },
    {
        "pattern": "AGENTS.md",
        "reason": "Upstream contributor-agent workflow instructions are not runtime code or product data.",
    },
    {
        "pattern": "**/__pycache__/**",
        "reason": "Interpreter-generated bytecode caches are not source or release inputs.",
    },
    {
        "pattern": "**/.pytest_cache/**",
        "reason": "Test-run caches are generated locally and are not source or release inputs.",
    },
    {
        "pattern": "**/.mypy_cache/**",
        "reason": "Type-check caches are generated locally and are not source or release inputs.",
    },
    {
        "pattern": "**/.ruff_cache/**",
        "reason": "Lint caches are generated locally and are not source or release inputs.",
    },
)
IGNORED_CACHE_PARTS = {
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Verify the exact LoopX v0.2.13 Git objects against Zyra's embedded "
            "source tree and regenerate its deterministic manifest and lock."
        )
    )
    parser.add_argument(
        "--source-root",
        default=str(PROJECT_ROOT.parent / "long-horizon-systems" / "loopx"),
    )
    parser.add_argument("--project-root", default=str(PROJECT_ROOT))
    parser.add_argument("--output", default="")
    return parser


def _git(source_root: Path, *arguments: str, binary: bool = False) -> str | bytes:
    result = subprocess.run(
        ["git", "-C", str(source_root), *arguments],
        check=False,
        capture_output=True,
        text=not binary,
        timeout=120,
    )
    if result.returncode != 0:
        stderr = (
            result.stderr.decode("utf-8", errors="replace")
            if binary
            else str(result.stderr)
        )
        raise RuntimeError(
            f"git {' '.join(arguments)} failed: {stderr.strip()}"
        )
    return result.stdout


def _tree_modes(source_root: Path) -> dict[str, str]:
    output = str(_git(source_root, "ls-tree", "-r", LOOPX_SOURCE_REF))
    modes: dict[str, str] = {}
    for line in output.splitlines():
        metadata, path = line.split("\t", 1)
        mode = metadata.split(" ", 1)[0]
        modes[path.replace("\\", "/")] = mode
    return modes


def _excluded(path: str) -> bool:
    return (
        path == "AGENTS.md"
        or path.startswith(".github/")
    )


def _archive_records(
    source_root: Path,
    embedded_root: Path,
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    modes = _tree_modes(source_root)
    excluded_counts = {item["pattern"]: 0 for item in EXCLUSIONS}
    records: list[dict[str, Any]] = []
    with tempfile.TemporaryDirectory(prefix="zyra-loopx-source-") as raw:
        archive = Path(raw) / "loopx-source.zip"
        _git(
            source_root,
            "archive",
            "--format=zip",
            f"--output={archive}",
            LOOPX_SOURCE_REF,
        )
        with zipfile.ZipFile(archive) as bundle:
            archive_files = {
                name: bundle.read(name)
                for name in bundle.namelist()
                if not name.endswith("/")
            }
        for path in sorted(archive_files, key=lambda item: item.encode("utf-8")):
            if path.startswith(".github/"):
                excluded_counts[".github/**"] += 1
                continue
            if path == "AGENTS.md":
                excluded_counts["AGENTS.md"] += 1
                continue
            target = embedded_root.joinpath(*PurePosixPath(path).parts)
            if not target.is_file():
                raise RuntimeError(f"embedded LoopX file is missing: {path}")
            expected = archive_files[path]
            actual = target.read_bytes()
            if actual != expected:
                raise RuntimeError(
                    f"embedded LoopX file differs from {LOOPX_SOURCE_REF}: {path}"
                )
            records.append(
                {
                    "path": path,
                    "size": len(expected),
                    "sha256": stable_digest_bytes(expected),
                    "executable": modes.get(path) == "100755",
                }
            )
    excluded_counts[".git/**"] = 0
    expected_paths = {str(item["path"]) for item in records}
    actual_paths = {
        path.relative_to(embedded_root).as_posix()
        for path in embedded_root.rglob("*")
        if path.is_file()
        and path.name != SOURCE_MANIFEST_NAME
        and not IGNORED_CACHE_PARTS.intersection(path.parts)
        and path.suffix.casefold() not in {".pyc", ".pyo"}
    }
    extra = sorted(actual_paths - expected_paths)
    missing = sorted(expected_paths - actual_paths)
    if extra or missing:
        raise RuntimeError(
            f"embedded source path set mismatch: extra={extra[:20]}, missing={missing[:20]}"
        )
    return records, excluded_counts


def stable_digest_bytes(content: bytes) -> str:
    import hashlib

    return hashlib.sha256(content).hexdigest()


def _inventory(
    embedded_root: Path,
    pyproject: Mapping[str, Any],
) -> dict[str, Any]:
    project = pyproject.get("project")
    tool = pyproject.get("tool")
    if not isinstance(project, Mapping) or not isinstance(tool, Mapping):
        raise RuntimeError("upstream pyproject sections are incomplete")
    scripts = project.get("scripts")
    if not isinstance(scripts, Mapping):
        raise RuntimeError("upstream entry points are missing")
    packages = {
        path.parent.relative_to(embedded_root).as_posix().replace("/", ".")
        for path in (embedded_root / "loopx").rglob("*.py")
    }
    extension_entry_points: dict[str, str] = {}
    packages_root = embedded_root / "packages"
    for extension_project in sorted(
        path for path in packages_root.iterdir() if path.is_dir()
    ):
        extension_pyproject = extension_project / "pyproject.toml"
        extension_source = extension_project / "src"
        if extension_source.is_dir():
            packages.update(
                path.parent.relative_to(extension_source).as_posix().replace(
                    "/", "."
                )
                for path in extension_source.rglob("*.py")
            )
        if extension_pyproject.is_file():
            with extension_pyproject.open("rb") as stream:
                extension_config = tomllib.load(stream)
            extension_project_config = extension_config.get("project")
            if isinstance(extension_project_config, Mapping):
                extension_scripts = extension_project_config.get("scripts")
                if isinstance(extension_scripts, Mapping):
                    extension_entry_points.update(
                        (str(key), str(value))
                        for key, value in extension_scripts.items()
                    )
    extensions = sorted(
        path.relative_to(embedded_root).as_posix()
        for path in embedded_root.rglob("extension.toml")
    )
    skills = sorted(
        path.relative_to(embedded_root).as_posix()
        for path in embedded_root.rglob("SKILL.md")
    )
    templates = sorted(
        path.relative_to(embedded_root).as_posix()
        for path in embedded_root.rglob("*")
        if path.is_file()
        and (
            "template" in path.name.casefold()
            or path.suffix.casefold() in {".j2", ".jinja", ".tmpl"}
        )
    )
    tests = sorted(
        path.relative_to(embedded_root).as_posix()
        for path in (embedded_root / "tests").rglob("*")
        if path.is_file()
        and not IGNORED_CACHE_PARTS.intersection(path.parts)
        and path.suffix.casefold() not in {".pyc", ".pyo"}
    )
    setuptools = tool.get("setuptools")
    package_data_map: Mapping[str, Any] = {}
    if isinstance(setuptools, Mapping):
        value = setuptools.get("package-data")
        if isinstance(value, Mapping):
            package_data_map = value
    package_data: list[str] = []
    for package_name, patterns in package_data_map.items():
        package_root = embedded_root.joinpath(*str(package_name).split("."))
        if not isinstance(patterns, Sequence) or isinstance(patterns, (str, bytes)):
            raise RuntimeError(f"invalid package data patterns for {package_name}")
        for pattern in patterns:
            matches = sorted(
                path
                for path in package_root.glob(str(pattern))
                if path.is_file()
            )
            if not matches:
                raise RuntimeError(
                    f"upstream package-data pattern has no match: {package_name}:{pattern}"
                )
            package_data.extend(
                path.relative_to(embedded_root).as_posix() for path in matches
            )
    return {
        "packages": sorted(packages),
        "entry_points": dict(sorted((str(k), str(v)) for k, v in scripts.items())),
        "extension_entry_points": dict(sorted(extension_entry_points.items())),
        "extensions": extensions,
        "skills": skills,
        "templates": templates,
        "package_data": sorted(set(package_data)),
        "upstream_tests": tests,
    }


def build(
    *,
    source_root: Path,
    project_root: Path,
    output_path: Path | None,
) -> dict[str, Any]:
    source_root = source_root.resolve()
    project_root = project_root.resolve()
    embedded_root = (
        project_root / "packages" / "integrations" / "loopx_runtime"
    ).resolve()
    tag_object = str(_git(source_root, "rev-parse", LOOPX_SOURCE_REF)).strip()
    source_commit = str(
        _git(source_root, "rev-parse", f"{LOOPX_SOURCE_REF}^{{commit}}")
    ).strip()
    object_type = str(_git(source_root, "cat-file", "-t", LOOPX_SOURCE_REF)).strip()
    if (
        tag_object != LOOPX_SOURCE_COMMIT
        or source_commit != LOOPX_SOURCE_TREE_COMMIT
        or object_type != "tag"
    ):
        raise RuntimeError(
            "LoopX source identity mismatch: "
            f"tag={tag_object}, peeled={source_commit}, type={object_type}"
        )
    with (embedded_root / "pyproject.toml").open("rb") as stream:
        pyproject = tomllib.load(stream)
    project = pyproject.get("project")
    if (
        not isinstance(project, Mapping)
        or project.get("name") != "loopx"
        or project.get("version") != LOOPX_VERSION
        or project.get("requires-python") != ">=3.11"
    ):
        raise RuntimeError("embedded LoopX pyproject identity is inconsistent")
    init_text = (embedded_root / "loopx" / "__init__.py").read_text(
        encoding="utf-8"
    )
    if f'__version__ = "{LOOPX_VERSION}"' not in init_text:
        raise RuntimeError("embedded LoopX runtime version is inconsistent")
    records, excluded_counts = _archive_records(source_root, embedded_root)
    inventory = _inventory(embedded_root, pyproject)
    tree_digest = source_manifest_digest(records)
    manifest: dict[str, Any] = {
        "schema": SOURCE_MANIFEST_SCHEMA,
        "version": LOOPX_VERSION,
        "source_ref": LOOPX_SOURCE_REF,
        "source_commit": LOOPX_SOURCE_COMMIT,
        "source_object_type": "annotated_tag",
        "source_tree_commit": LOOPX_SOURCE_TREE_COMMIT,
        "tree_digest": tree_digest,
        "file_count": len(records),
        "files": records,
        "exclusions": [
            {
                **item,
                "excluded_file_count": excluded_counts[item["pattern"]],
            }
            for item in EXCLUSIONS
        ],
        **inventory,
    }
    manifest_path = embedded_root / SOURCE_MANIFEST_NAME
    _write_json(manifest_path, manifest)
    manifest_sha256 = sha256_file(manifest_path)
    lock: dict[str, Any] = {
        "schema": PACKAGE_LOCK_SCHEMA,
        "slice": {
            "slice_id": "P2-S01-04",
            "base_commit": "3c4d1092187b1777468cad0ce2a772244d012197",
        },
        "package": {
            "name": "loopx",
            "version": LOOPX_VERSION,
            "source_ref": LOOPX_SOURCE_REF,
            "source_commit": LOOPX_SOURCE_COMMIT,
            "source_object_type": "annotated_tag",
            "source_tree_commit": LOOPX_SOURCE_TREE_COMMIT,
            "source_role": "supplementary_implementation",
            "migration_mode": "pinned_embedded_source_integration",
            "language": "python",
            "requires_python": ">=3.11",
            "runtime_dependencies": [],
            "runtime_dependency_imports": [],
            "packages": inventory["packages"],
            "entry_points": inventory["entry_points"],
            "extension_entry_points": inventory["extension_entry_points"],
            "package_data": inventory["package_data"],
            "state_owner": "loopx_private_control",
            "line_bucket": "runtime-assets/vendor-like",
        },
        "source_manifest": {
            "schema": SOURCE_MANIFEST_SCHEMA,
            "path": (
                "packages/integrations/loopx_runtime/"
                + SOURCE_MANIFEST_NAME
            ),
            "sha256": manifest_sha256,
            "tree_digest": tree_digest,
            "file_count": len(records),
        },
        "artifacts": {},
        "profiles": {
            "pinned_embedded_source": {
                "source": "packages/integrations/loopx_runtime",
                "network_access": False,
                "archive_extraction": False,
                "archive_fallback": False,
                "root_source_fallback": False,
                "user_level_fallback": False,
                "workspace_state": "{workspace}/.zyra/loopx/state",
                "retired_install_path": "{workspace}/.zyra/loopx/install",
            }
        },
        "doctor": {
            "schema": "zyra.loopx-embedded-doctor-metadata/v1",
            "required_deep_checks": [
                "package-identity",
                "embedded-source-integrity",
                "embedded-runtime-layout",
                "archive-entry-retired",
                "import-and-cli-entry",
                "extension-skill-resource-discovery",
                "workspace-private-state",
            ],
            "required_identity": {
                "version": LOOPX_VERSION,
                "source_ref": LOOPX_SOURCE_REF,
                "source_commit": LOOPX_SOURCE_COMMIT,
                "source_tree_commit": LOOPX_SOURCE_TREE_COMMIT,
                "tree_digest": tree_digest,
                "entry_points": inventory["entry_points"],
            },
            "workspace_state_contract": "{workspace}/.zyra/loopx/state",
            "retired_install_path_ignored": True,
        },
        "release": {
            "packaged_runtime": True,
            "supplementary": True,
            "offline": True,
            "source_repository_required_at_runtime": False,
            "archive_install_required": False,
            "first_task_install_required": False,
        },
        "build": {
            "builder": "scripts/release/build_loopx_embedded_source.py",
            "reproducible": True,
            "cross_platform_tree_digest": True,
        },
    }
    lock["lock_digest"] = stable_digest(lock)
    lock_path = project_root / "config" / "loopx" / "package-lock.json"
    packaged_root = (
        project_root
        / "packages"
        / "integrations"
        / "zyra_integrations"
        / "loopx"
        / "runtime"
    )
    _write_json(lock_path, lock)
    shutil.copyfile(manifest_path, packaged_root / SOURCE_MANIFEST_NAME)
    shutil.copyfile(lock_path, packaged_root / "package-lock.json")
    result = {
        "schema": "zyra.loopx-embedded-source-build/v1",
        "ready": True,
        "version": LOOPX_VERSION,
        "source_ref": LOOPX_SOURCE_REF,
        "source_commit": LOOPX_SOURCE_COMMIT,
        "source_object_type": "annotated_tag",
        "source_tree_commit": LOOPX_SOURCE_TREE_COMMIT,
        "tree_digest": tree_digest,
        "source_file_count": len(records),
        "manifest": str(manifest_path),
        "manifest_sha256": manifest_sha256,
        "package_lock": str(lock_path),
        "package_lock_digest": lock["lock_digest"],
        "archive_artifact_count": 0,
        "inventory": {
            key: len(value) if not isinstance(value, Mapping) else len(value)
            for key, value in inventory.items()
        },
        "exclusions": manifest["exclusions"],
    }
    if output_path is not None:
        _write_json(output_path, result)
    return result


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def run(argv: Sequence[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    result = build(
        source_root=Path(arguments.source_root),
        project_root=Path(arguments.project_root),
        output_path=Path(arguments.output).resolve() if arguments.output else None,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


def main() -> None:
    raise SystemExit(run())


if __name__ == "__main__":
    main()
