from __future__ import annotations

from collections.abc import Iterable

from .models import (
    ActionAccess,
    ActionDefinition,
    ActionRisk,
    ActionSource,
    ActionTargetKind,
    SchemaValueType,
    array_rule,
    boolean_rule,
    integer_rule,
    number_rule,
    object_rule,
    string_rule,
)


BROWSER_USE_REGISTRY = ActionSource(
    repository="browser-use",
    path="browser_use/tools/registry/service.py",
    symbol="Registry.action/execute_action/create_action_model",
    role="primary_implementation",
    strategy="semantic_port",
    notes=(
        "Zyra owns immutable action definitions and validation.",
        "Source parameter injection is replaced by explicit Zyra ports.",
        "Sensitive replacement is delegated to the Zyra secret policy before permission.",
    ),
)

BROWSER_USE_TOOLS = ActionSource(
    repository="browser-use",
    path="browser_use/tools/service.py",
    symbol="Tools default action handlers",
    role="primary_implementation",
    strategy="decomposed_port",
    notes=(
        "Handlers are split across registry, selector, security and executor boundaries.",
        "Browser-use runtime remains a transport adapter, not action or policy owner.",
    ),
)

BROWSER_USE_ACTOR = ActionSource(
    repository="browser-use",
    path="browser_use/actor/{page,element,mouse,utils}.py",
    symbol="Page/Element/Mouse",
    role="primary_implementation",
    strategy="selective_direct_port",
    notes=(
        "Backend-node and coordinate execution mechanics are retained behind Zyra receipts.",
        "Every mutating operation requires selector identity and a consumed exact grant.",
    ),
)

BROWSER_USE_SECURITY = ActionSource(
    repository="browser-use",
    path="browser_use/browser/watchdogs/security_watchdog.py",
    symbol="SecurityWatchdog",
    role="primary_implementation",
    strategy="semantic_port",
    notes=(
        "Pre-navigation, redirect-complete and new-target checks share one Zyra policy.",
        "DNS/IP classification is added before network dispatch.",
    ),
)

BROWSER_USE_FILES = ActionSource(
    repository="browser-use",
    path="browser_use/filesystem/file_system.py;browser_use/tools/service.py::upload_file",
    symbol="FileSystem/upload_file/downloaded_files",
    role="primary_implementation",
    strategy="semantic_port",
    notes=(
        "Zyra artifact/workspace ownership replaces the upstream private file store.",
        "Resolved-path and symlink containment are checked at the side-effect boundary.",
    ),
)

CLAUDE_PERMISSION = ActionSource(
    repository="claude-code-best",
    path="src/cli/src/utils/permissions/*;src/QueryEngine.ts",
    symbol="allow/deny/ask exact-call continuation",
    role="supplementary_implementation",
    strategy="existing_owner_bridge",
    notes=(
        "M1-03A ToolPermissionRuntime remains the only decision owner.",
        "04C contributes browser risk attributes and consumes one-use grants.",
    ),
)

OMP_PREFLIGHT = ActionSource(
    repository="oh-my-pi",
    path="packages/coding-agent/src/tools/**;packages/hashline/**",
    symbol="tool wrapper/hooks/hashline preflight",
    role="supplementary_implementation",
    strategy="semantic_port",
    notes=(
        "Before/after hook envelopes cannot execute the action.",
        "Hashline-style request and selector digests reject stale replay.",
        "yolo, subagent yolo and advisor bypass are rejected.",
    ),
)


def _sources(*extra: ActionSource) -> tuple[ActionSource, ...]:
    return (BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, *extra)


def _element_sources(*extra: ActionSource) -> tuple[ActionSource, ...]:
    return (BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_ACTOR, CLAUDE_PERMISSION, OMP_PREFLIGHT, *extra)


def _url_arguments(*, required: bool = True) -> tuple:
    return (
        string_rule(
            "url",
            required=required,
            min_length=1,
            max_length=16_384,
            description="Absolute http(s) or policy-owned file URL.",
        ),
        boolean_rule("new_tab", default=False, description="Open in a new target after policy validation."),
        number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
        number_rule("settle_seconds", minimum=0.0, maximum=10.0, default=0.0),
    )


def _selector_arguments(*, file_input: bool = False) -> tuple:
    kind = "file input" if file_input else "element"
    return (
        string_rule("selector_ref", min_length=8, max_length=256, identifier=True, description=f"Opaque 04B {kind} ref."),
        integer_rule("index", minimum=0, maximum=1_000_000, aliases=("element_id",)),
        string_rule("id", min_length=1, max_length=4_096, identifier=True),
        string_rule("selector", min_length=1, max_length=8_192),
        string_rule("css_selector", min_length=1, max_length=8_192),
        integer_rule("backend_node_id", minimum=1, maximum=2_147_483_647),
        string_rule("selector_revision_id", max_length=256, identifier=True),
        integer_rule("selector_generation", minimum=0),
        string_rule("target_id", max_length=256, identifier=True),
        string_rule("cdp_session_id", max_length=256, identifier=True),
        string_rule("frame_id", max_length=256, identifier=True),
        string_rule("document_loader_id", max_length=512, identifier=True),
        integer_rule("target_generation", minimum=0),
        integer_rule("cdp_generation", minimum=0),
        string_rule("capture_digest", max_length=128, identifier=True),
    )


def default_action_definitions() -> tuple[ActionDefinition, ...]:
    definitions = (
        ActionDefinition(
            name="open_url",
            source_name="navigate",
            description="Navigate to a policy-approved URL with DNS/IP and redirect fencing.",
            arguments=_url_arguments(required=True),
            aliases=("navigate", "goto", "open"),
            access=frozenset({ActionAccess.NETWORK, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            timeout_seconds=30.0,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_SECURITY, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("navigation", "network", "redirect_checked", "dns_pinned"),
        ),
        ActionDefinition(
            name="go_back",
            source_name="go_back",
            description="Navigate to the previous history entry after revalidating the resulting URL.",
            arguments=(
                number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
                number_rule("settle_seconds", minimum=0.0, maximum=10.0, default=0.0),
            ),
            aliases=("back",),
            access=frozenset({ActionAccess.NETWORK, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_SECURITY, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("navigation", "history", "redirect_checked"),
        ),
        ActionDefinition(
            name="reload_page",
            source_name="reload",
            description="Reload the focused page while preserving target and network policy identity.",
            arguments=(
                boolean_rule("ignore_cache", default=False),
                string_rule("script_to_evaluate_on_load", max_length=32_768),
                number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
            ),
            aliases=("reload", "refresh"),
            access=frozenset({ActionAccess.NETWORK, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_ACTOR, BROWSER_USE_SECURITY, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("navigation", "network"),
        ),
        ActionDefinition(
            name="extract_text",
            source_name="extract",
            description="Extract visible text through a bounded, read-only browser state query.",
            arguments=(
                string_rule("query", max_length=8_192),
                boolean_rule("extract_links", default=True),
                boolean_rule("extract_images", default=False),
                integer_rule("start_from_char", minimum=0, maximum=50_000_000, default=0),
                integer_rule("max_chars", minimum=256, maximum=2_000_000, default=100_000),
                boolean_rule("include_hidden", default=False),
            ),
            aliases=("extract", "read_page"),
            access=frozenset({ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.PASSIVE,
            target_kind=ActionTargetKind.PAGE,
            result_budget_chars=100_000,
            sources=_sources(BROWSER_USE_SECURITY),
            tags=("dom_query", "artifact_externalized"),
        ),
        ActionDefinition(
            name="snapshot_state",
            source_name="find_elements",
            description="Capture bounded DOM, AX and selector state owned by 04B.",
            arguments=(
                string_rule("selector", max_length=8_192),
                array_rule("attributes", item_type=SchemaValueType.STRING, max_items=128),
                integer_rule("max_results", minimum=1, maximum=10_000, default=500),
                boolean_rule("include_text", default=True),
                boolean_rule("include_ax", default=True),
                boolean_rule("include_dom_snapshot", default=True),
                boolean_rule("include_screenshot", default=False),
                string_rule("marker", max_length=512),
            ),
            aliases=("find_elements", "state", "read_state", "capture_trace"),
            access=frozenset({ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.PASSIVE,
            target_kind=ActionTargetKind.PAGE,
            result_budget_chars=200_000,
            sources=_sources(BROWSER_USE_SECURITY),
            tags=("dom_query", "selector_revision", "04b_owner"),
        ),
        ActionDefinition(
            name="search_page",
            source_name="search_page",
            description="Search page text using a fixed JS template and JSON-bound parameters.",
            arguments=(
                string_rule("pattern", required=True, min_length=1, max_length=8_192),
                boolean_rule("regex", default=False),
                boolean_rule("case_sensitive", default=False),
                integer_rule("context_chars", minimum=0, maximum=10_000, default=120),
                string_rule("css_scope", max_length=8_192),
                integer_rule("max_results", minimum=1, maximum=10_000, default=100),
            ),
            aliases=("find_on_page",),
            access=frozenset({ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.PASSIVE,
            target_kind=ActionTargetKind.PAGE,
            result_budget_chars=100_000,
            sources=_sources(),
            tags=("fixed_script", "dom_query"),
        ),
        ActionDefinition(
            name="click_element",
            source_name="click",
            description="Click a current 04B selector after visibility, occlusion, scroll and exact-grant checks.",
            arguments=(
                *_selector_arguments(),
                string_rule("url", max_length=16_384, description="Optional current-page hint; never replaces selector identity."),
                string_rule("button", enum=("left", "right", "middle"), default="left"),
                integer_rule("click_count", minimum=1, maximum=3, default=1),
                boolean_rule("scroll_into_view", default=True),
                boolean_rule("require_unoccluded", default=True),
                number_rule("coordinate_x", minimum=0, maximum=1_000_000),
                number_rule("coordinate_y", minimum=0, maximum=1_000_000),
                array_rule("modifiers", item_type=SchemaValueType.STRING, max_items=4),
                number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
            ),
            aliases=("click",),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(),
            tags=("selector_bound", "occlusion_checked", "scroll_checked"),
        ),
        ActionDefinition(
            name="input_text",
            source_name="input",
            description="Type text into a current selector with secret-aware result redaction.",
            arguments=(
                *_selector_arguments(),
                string_rule("text", required=True, max_length=1_000_000, secret_capable=True),
                boolean_rule("clear", default=True),
                boolean_rule("verify_value", default=True),
                boolean_rule("dispatch_change", default=True),
                number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
            ),
            aliases=("input", "type_text", "fill"),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(),
            tags=("selector_bound", "secret_capable", "value_verified"),
        ),
        ActionDefinition(
            name="submit_form",
            source_name="click/input",
            description="Submit a form only after resolving the action URL and external side effect.",
            arguments=(
                *_selector_arguments(),
                string_rule("form_action_url", max_length=16_384),
                string_rule("method", enum=("get", "post", "dialog")),
                object_rule("field_summary"),
                boolean_rule("confirm_external_side_effect", default=False),
                number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
            ),
            aliases=("submit",),
            access=frozenset({ActionAccess.BROWSER_MUTATION, ActionAccess.NETWORK, ActionAccess.EXTERNAL_SIDE_EFFECT}),
            base_risk=ActionRisk.HIGH,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(BROWSER_USE_SECURITY),
            tags=("form", "external_side_effect", "network"),
        ),
        ActionDefinition(
            name="upload_file",
            source_name="upload_file",
            description="Upload an explicitly authorized artifact/workspace file through a current file input.",
            arguments=(
                *_selector_arguments(file_input=True),
                string_rule("path", required=True, min_length=1, max_length=32_768, aliases=("file_path",)),
                string_rule("artifact_id", max_length=256, identifier=True),
                string_rule("expected_sha256", pattern=r"(?:sha256:)?[0-9a-fA-F]{64}"),
                integer_rule("max_bytes", minimum=1, maximum=10_000_000_000, default=100_000_000),
                boolean_rule("allow_download_artifact", default=True),
            ),
            aliases=("upload",),
            access=frozenset({ActionAccess.FILE_READ, ActionAccess.BROWSER_MUTATION, ActionAccess.EXTERNAL_SIDE_EFFECT}),
            base_risk=ActionRisk.HIGH,
            target_kind=ActionTargetKind.FILE_INPUT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(BROWSER_USE_FILES),
            tags=("file", "upload", "containment", "artifact_provenance"),
        ),
        ActionDefinition(
            name="download_file",
            source_name="click/downloaded_files",
            description="Trigger a bounded download and accept only a contained sanitized result.",
            arguments=(
                *_selector_arguments(),
                string_rule("url", max_length=16_384),
                string_rule("suggested_filename", max_length=512),
                integer_rule("max_bytes", minimum=1, maximum=10_000_000_000, default=500_000_000),
                number_rule("settle_seconds", minimum=0.0, maximum=30.0, default=2.0),
            ),
            aliases=("download",),
            access=frozenset({ActionAccess.NETWORK, ActionAccess.FILE_WRITE, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.SENSITIVE,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(BROWSER_USE_FILES, BROWSER_USE_SECURITY),
            tags=("file", "download", "filename_sanitized", "containment"),
        ),
        ActionDefinition(
            name="collect_downloads",
            source_name="downloaded_files",
            description="Project completed session-owned downloads into Zyra artifacts.",
            arguments=(
                number_rule("settle_seconds", minimum=0.0, maximum=30.0, default=1.0),
                integer_rule("max_files", minimum=1, maximum=1_000, default=64),
                integer_rule("max_total_bytes", minimum=1, maximum=20_000_000_000, default=1_000_000_000),
                boolean_rule("include_incomplete", default=False),
            ),
            aliases=("downloads", "collect_download"),
            access=frozenset({ActionAccess.FILE_READ}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            result_budget_chars=100_000,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_FILES, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("download", "artifact_externalized"),
        ),
        ActionDefinition(
            name="select_dropdown",
            source_name="select_dropdown_option",
            description="Select one or more options on a current select element.",
            arguments=(
                *_selector_arguments(),
                string_rule("option", max_length=65_536, secret_capable=True),
                array_rule("options", item_type=SchemaValueType.STRING, max_items=1_000),
                string_rule("match", enum=("value", "label", "index"), default="label"),
                boolean_rule("dispatch_change", default=True),
            ),
            aliases=("select", "select_option"),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.SELECT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(),
            tags=("selector_bound", "special_control", "select"),
        ),
        ActionDefinition(
            name="get_dropdown_options",
            source_name="get_dropdown_options",
            description="Read options from a current select element without changing it.",
            arguments=(*_selector_arguments(), integer_rule("max_options", minimum=1, maximum=10_000, default=1_000)),
            aliases=("dropdown_options",),
            access=frozenset({ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.LOW,
            target_kind=ActionTargetKind.SELECT,
            selector_required=True,
            result_budget_chars=100_000,
            sources=_element_sources(),
            tags=("selector_bound", "special_control", "select"),
        ),
        ActionDefinition(
            name="check_element",
            source_name="click/check",
            description="Set a checkbox or radio control to the requested checked state.",
            arguments=(
                *_selector_arguments(),
                boolean_rule("checked", default=True),
                boolean_rule("dispatch_change", default=True),
            ),
            aliases=("check", "uncheck"),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(),
            tags=("selector_bound", "special_control", "checkbox"),
        ),
        ActionDefinition(
            name="drag_element",
            source_name="drag_to",
            description="Drag a current selector to another selector or bounded viewport coordinate.",
            arguments=(
                *_selector_arguments(),
                string_rule("target_selector_ref", max_length=256, identifier=True),
                number_rule("target_x", minimum=0, maximum=1_000_000),
                number_rule("target_y", minimum=0, maximum=1_000_000),
                integer_rule("steps", minimum=1, maximum=200, default=10),
                integer_rule("duration_ms", minimum=0, maximum=30_000, default=500),
            ),
            aliases=("drag", "drag_to"),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.SENSITIVE,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(),
            tags=("selector_bound", "geometry", "mouse"),
        ),
        ActionDefinition(
            name="hover_element",
            source_name="hover",
            description="Move the pointer to the center of a current unoccluded selector.",
            arguments=(
                *_selector_arguments(),
                boolean_rule("scroll_into_view", default=True),
                boolean_rule("require_unoccluded", default=True),
            ),
            aliases=("hover",),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.LOW,
            target_kind=ActionTargetKind.ELEMENT,
            permission_required=True,
            selector_required=True,
            sources=_element_sources(),
            tags=("selector_bound", "occlusion_checked", "mouse"),
        ),
        ActionDefinition(
            name="scroll_page",
            source_name="scroll",
            description="Scroll a page or selector by bounded CSS-pixel deltas.",
            arguments=(
                *_selector_arguments(),
                boolean_rule("down", default=True),
                number_rule("pages", minimum=-100.0, maximum=100.0, default=1.0),
                number_rule("delta_x", minimum=-10_000_000, maximum=10_000_000, default=0.0),
                number_rule("delta_y", minimum=-10_000_000, maximum=10_000_000),
                boolean_rule("smooth", default=False),
            ),
            aliases=("scroll",),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.LOW,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_ACTOR, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("scroll", "geometry"),
        ),
        ActionDefinition(
            name="scroll_to_text",
            source_name="find_text",
            description="Locate visible text and scroll it into the viewport with a fixed query.",
            arguments=(
                string_rule("text", required=True, min_length=1, max_length=8_192),
                boolean_rule("case_sensitive", default=False),
                integer_rule("occurrence", minimum=1, maximum=10_000, default=1),
            ),
            aliases=("find_text",),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.LOW,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            sources=_sources(BROWSER_USE_ACTOR, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("scroll", "fixed_script"),
        ),
        ActionDefinition(
            name="send_keys",
            source_name="send_keys",
            description="Send a bounded keyboard sequence to the focused page or selector.",
            arguments=(
                string_rule("keys", required=True, min_length=1, max_length=65_536, secret_capable=True),
                *_selector_arguments(),
                integer_rule("repeat", minimum=1, maximum=1_000, default=1),
                integer_rule("delay_ms", minimum=0, maximum=10_000, default=0),
            ),
            aliases=("press", "keyboard"),
            access=frozenset({ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.SENSITIVE,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_ACTOR, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("keyboard", "shortcut_checked"),
        ),
        ActionDefinition(
            name="clipboard_read",
            source_name="clipboard",
            description="Read browser clipboard text only when explicitly authorized.",
            arguments=(integer_rule("max_chars", minimum=1, maximum=1_000_000, default=100_000),),
            aliases=("read_clipboard",),
            access=frozenset({ActionAccess.CLIPBOARD, ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.HIGH,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            result_budget_chars=100_000,
            sources=(BROWSER_USE_REGISTRY, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("clipboard", "secret_risk"),
        ),
        ActionDefinition(
            name="clipboard_write",
            source_name="clipboard",
            description="Write text to browser clipboard only when explicitly authorized.",
            arguments=(string_rule("text", required=True, max_length=1_000_000, secret_capable=True),),
            aliases=("write_clipboard",),
            access=frozenset({ActionAccess.CLIPBOARD, ActionAccess.EXTERNAL_SIDE_EFFECT}),
            base_risk=ActionRisk.HIGH,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("clipboard", "secret_risk", "external_side_effect"),
        ),
        ActionDefinition(
            name="take_screenshot",
            source_name="screenshot",
            description="Capture a bounded screenshot and externalize bytes as a Zyra artifact.",
            arguments=(
                string_rule("file_name", max_length=512),
                boolean_rule("full_page", default=False),
                string_rule("format", enum=("png", "jpeg", "webp"), default="png"),
                integer_rule("quality", minimum=1, maximum=100, default=90),
                boolean_rule("from_surface", default=True),
                boolean_rule("capture_beyond_viewport", default=False),
            ),
            aliases=("screenshot",),
            access=frozenset({ActionAccess.READ_ONLY, ActionAccess.FILE_WRITE}),
            base_risk=ActionRisk.LOW,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            result_budget_chars=10_000,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_ACTOR, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("artifact", "image", "secret_redacted"),
        ),
        ActionDefinition(
            name="save_as_pdf",
            source_name="save_as_pdf",
            description="Print the current page to a contained PDF artifact.",
            arguments=(
                string_rule("file_name", max_length=512),
                boolean_rule("print_background", default=True),
                boolean_rule("landscape", default=False),
                number_rule("scale", minimum=0.1, maximum=2.0, default=1.0),
                string_rule("paper_format", enum=("Letter", "Legal", "Tabloid", "A0", "A1", "A2", "A3", "A4", "A5", "A6"), default="Letter"),
                boolean_rule("display_header_footer", default=False),
            ),
            aliases=("pdf", "print_pdf"),
            access=frozenset({ActionAccess.READ_ONLY, ActionAccess.FILE_WRITE}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            result_budget_chars=10_000,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_FILES, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("artifact", "pdf", "filename_sanitized"),
        ),
        ActionDefinition(
            name="evaluate_js",
            source_name="evaluate",
            description="Execute explicitly authorized browser JavaScript; prompt text is never treated as a sandbox.",
            arguments=(
                string_rule("code", required=True, min_length=1, max_length=256_000, secret_capable=True),
                boolean_rule("await_promise", default=True),
                boolean_rule("return_by_value", default=True),
                boolean_rule("user_gesture", default=False),
                integer_rule("max_result_chars", minimum=256, maximum=2_000_000, default=20_000),
                number_rule("timeout_seconds", minimum=0.1, maximum=120.0, default=30.0),
            ),
            aliases=("evaluate", "javascript", "js"),
            access=frozenset({ActionAccess.SCRIPT, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.HIGH,
            target_kind=ActionTargetKind.PAGE,
            permission_required=True,
            result_budget_chars=20_000,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, BROWSER_USE_ACTOR, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("arbitrary_script", "explicit_only", "not_sandboxed"),
        ),
        ActionDefinition(
            name="list_targets",
            source_name="switch_tab",
            description="List browser targets as a read-only, bounded projection.",
            arguments=(
                boolean_rule("include_internal", default=False),
                integer_rule("max_targets", minimum=1, maximum=10_000, default=100),
            ),
            aliases=("tabs", "list_tabs"),
            access=frozenset({ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.PASSIVE,
            target_kind=ActionTargetKind.TARGET,
            result_budget_chars=100_000,
            sources=_sources(),
            tags=("target", "read_only"),
        ),
        ActionDefinition(
            name="focus_target",
            source_name="switch_tab",
            description="Focus a known target and invalidate selectors from the previous focus generation.",
            arguments=(
                string_rule("target_id", required=True, min_length=1, max_length=256, identifier=True),
                boolean_rule("activate", default=True),
                integer_rule("expected_target_generation", minimum=0),
            ),
            aliases=("switch_tab", "focus_tab"),
            access=frozenset({ActionAccess.TARGET_CONTROL, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.GUARDED,
            target_kind=ActionTargetKind.TARGET,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("target", "selector_invalidation"),
        ),
        ActionDefinition(
            name="close_target",
            source_name="close_tab",
            description="Close a known non-owner browser target after exact permission.",
            arguments=(
                string_rule("target_id", required=True, min_length=1, max_length=256, identifier=True),
                boolean_rule("allow_last_target", default=False),
            ),
            aliases=("close_tab",),
            access=frozenset({ActionAccess.TARGET_CONTROL, ActionAccess.BROWSER_MUTATION}),
            base_risk=ActionRisk.SENSITIVE,
            target_kind=ActionTargetKind.TARGET,
            permission_required=True,
            sources=(BROWSER_USE_REGISTRY, BROWSER_USE_TOOLS, CLAUDE_PERMISSION, OMP_PREFLIGHT),
            tags=("target", "destructive"),
        ),
        ActionDefinition(
            name="wait",
            source_name="wait",
            description="Wait for a bounded interval without granting any browser side effect.",
            arguments=(number_rule("seconds", minimum=0.0, maximum=30.0, default=3.0),),
            aliases=("sleep",),
            access=frozenset({ActionAccess.READ_ONLY}),
            base_risk=ActionRisk.PASSIVE,
            target_kind=ActionTargetKind.NONE,
            sources=_sources(),
            tags=("control", "bounded"),
        ),
    )
    _validate_catalog(definitions)
    return definitions


def _validate_catalog(definitions: Iterable[ActionDefinition]) -> None:
    names: set[str] = set()
    aliases: set[str] = set()
    for definition in definitions:
        if definition.name in names or definition.name in aliases:
            raise ValueError(f"duplicate browser action catalog identity: {definition.name}")
        names.add(definition.name)
        for alias in definition.aliases:
            if alias in names or alias in aliases:
                raise ValueError(f"duplicate browser action catalog alias: {alias}")
            aliases.add(alias)
