import { createHash, randomUUID } from "node:crypto";
export type V=null|boolean|number|string|V[]|{[k:string]:V}; export type O={[k:string]:V};
export type Phase="validate"|"prepare"|"effect"|"receipt"|"commit"|"ack"|"project";
export interface Id {runId:string;sessionId:string;turnId:string;transitionId:string;attemptId:string;requestId:string;toolCallId:string;idempotencyKey:string;expectedRevision:number}
export interface Cmd {domain:string;operation:string;id:Id;readSet:string[];writeSet:string[];payload:O;effect:boolean;owner:"typescript"}
export interface Effect {idempotencyKey:string;attemptId:string;terminal:boolean;ok:boolean;digest:string;reconciled:boolean;error:string}
export interface Receipt {id:Id;domain:string;operation:string;phase:Phase;status:"pending"|"effect"|"committed"|"acked"|"quarantined";before:number;after:number;commandDigest:string;stateDigest:string;effect:Effect|null;outbox:string[];duplicate:boolean;error:string}
export interface Snapshot {owner:"typescript";revision:number;state:O;digest:string;pending:Receipt[];committed:Receipt[];effects:Effect[];outbox:Array<{id:string;delivered:boolean;payload:O}>}
export class InvariantError extends Error {readonly code:string;constructor(code:string,message:string){super(message);this.code=code;this.name="InvariantError"}}
export function json(v:unknown):string{if(Array.isArray(v))return"["+v.map(json).join(",")+"]";if(v&&typeof v==="object"){const o=v as Record<string,unknown>;return"{"+Object.keys(o).sort().map(k=>JSON.stringify(k)+":"+json(o[k])).join(",")+"}"}return JSON.stringify(v)}
export function digest(v:unknown):string{return"sha256:"+createHash("sha256").update(json(v)).digest("hex")}
export function identity(runId:string,sessionId:string,transitionId="",expectedRevision=0):Id{const t=transitionId||"transition_"+randomUUID();return{runId,sessionId,turnId:"turn_"+sessionId,transitionId:t,attemptId:t+":attempt:1",requestId:"request_"+randomUUID(),toolCallId:"",idempotencyKey:digest([runId,sessionId,t]),expectedRevision}}
export function cmd(domain:string,operation:string,id:Id,payload:O,effect=false):Cmd{return{domain,operation,id,payload,effect,owner:"typescript",readSet:[domain+":revision"],writeSet:[domain+":"+operation]}}
function merge(a:O,b:O):O{const o=structuredClone(a);for(const[k,v]of Object.entries(b)){const x=o[k];o[k]=v&&typeof v==="object"&&!Array.isArray(v)&&x&&typeof x==="object"&&!Array.isArray(x)?merge(x as O,v as O):structuredClone(v)}return o}
export class Journal{
 private rev=0;private data:O={};private p=new Map<string,Receipt>();private c=new Map<string,Receipt>();private e=new Map<string,Effect>();private q=new Map<string,{id:string;delivered:boolean;payload:O}>();private locks=new Map<string,string>();
 get revision(){return this.rev} get state(){return structuredClone(this.data)}
 prepare(x:Cmd):Receipt{const done=this.c.get(x.id.transitionId);if(done)return{...structuredClone(done),duplicate:true};const old=this.p.get(x.id.transitionId);if(old)return{...structuredClone(old),duplicate:true};this.check(x);for(const k of x.writeSet){const owner=this.locks.get(k);if(owner&&owner!==x.id.transitionId)throw new InvariantError("write_conflict",k)}const r:Receipt={id:structuredClone(x.id),domain:x.domain,operation:x.operation,phase:"prepare",status:"pending",before:this.rev,after:this.rev,commandDigest:digest(x),stateDigest:digest(this.data),effect:null,outbox:[],duplicate:false,error:""};this.p.set(x.id.transitionId,r);for(const k of x.writeSet)this.locks.set(k,x.id.transitionId);return structuredClone(r)}
 effect(x:Cmd,value:O,error=""):Effect{const p=this.need(x);const old=this.e.get(x.id.idempotencyKey);if(old?.terminal)return structuredClone(old);const e={idempotencyKey:x.id.idempotencyKey,attemptId:x.id.attemptId,terminal:true,ok:!error,digest:digest(value),reconciled:false,error};this.e.set(e.idempotencyKey,e);p.phase="receipt";p.status="effect";p.effect=e;return structuredClone(e)}
 commit(x:Cmd,patch:O,events:O[]):Receipt{const old=this.c.get(x.id.transitionId);if(old)return{...structuredClone(old),duplicate:true};const p=this.need(x);if(x.effect&&!this.e.get(x.id.idempotencyKey)?.terminal)throw new InvariantError("effect_missing","terminal receipt required");if(x.id.expectedRevision!==this.rev)throw new InvariantError("stale_revision","CAS mismatch");this.data=merge(this.data,patch);this.rev++;p.phase="commit";p.status="committed";p.after=this.rev;p.stateDigest=digest(this.data);p.outbox=events.map((v,i)=>{const id=x.id.transitionId+":outbox:"+(i+1);this.q.set(id,{id,delivered:false,payload:structuredClone(v)});return id});this.p.delete(x.id.transitionId);this.c.set(x.id.transitionId,p);for(const k of x.writeSet)if(this.locks.get(k)===x.id.transitionId)this.locks.delete(k);return structuredClone(p)}
 ack(t:string):Receipt{const r=this.c.get(t);if(!r)throw new InvariantError("commit_missing",t);r.phase="ack";r.status="acked";return structuredClone(r)}
 project(id:string){const x=this.q.get(id);if(!x)throw new InvariantError("outbox_missing",id);x.delivered=true}
 reconcile(x:Cmd,physical:"present"|"absent"|"unknown",value:O={}):Receipt{const done=this.c.get(x.id.transitionId);if(done)return{...structuredClone(done),duplicate:true};const p=this.p.get(x.id.transitionId)||this.prepare(x);if(physical==="unknown"){const r=this.p.get(x.id.transitionId)!;r.status="quarantined";r.error="effect_outcome_unknown";return structuredClone(r)}if(physical==="present"){const e=this.effect(x,value);e.reconciled=true;this.e.set(e.idempotencyKey,e)}return structuredClone(this.p.get(x.id.transitionId)||p)}
 snapshot():Snapshot{return{owner:"typescript",revision:this.rev,state:structuredClone(this.data),digest:digest(this.data),pending:[...this.p.values()].map((value) => structuredClone(value)),committed:[...this.c.values()].map((value) => structuredClone(value)),effects:[...this.e.values()].map((value) => structuredClone(value)),outbox:[...this.q.values()].map((value) => structuredClone(value))}}
 restore(s:Snapshot){if(s.owner!=="typescript")throw new InvariantError("stale_owner","logical owner mismatch");if(digest(s.state)!==s.digest)throw new InvariantError("snapshot_digest","corrupt snapshot");this.rev=s.revision;this.data=structuredClone(s.state);this.p.clear();this.c.clear();this.e.clear();this.q.clear();for(const x of s.pending)this.p.set(x.id.transitionId,structuredClone(x));for(const x of s.committed)this.c.set(x.id.transitionId,structuredClone(x));for(const x of s.effects)this.e.set(x.idempotencyKey,structuredClone(x));for(const x of s.outbox)this.q.set(x.id,structuredClone(x))}
 private check(x:Cmd){if(x.owner!=="typescript"||x.payload.logical_owner==="python")throw new InvariantError("stale_owner","Python cannot own logical next state");if(!x.id.transitionId||!x.id.idempotencyKey)throw new InvariantError("identity_missing","stable identity required");if(x.id.expectedRevision!==this.rev)throw new InvariantError("stale_revision","expected revision mismatch");if(new Set(x.writeSet).size!==x.writeSet.length)throw new InvariantError("duplicate_write","write set must be unique")}
 private need(x:Cmd){const p=this.p.get(x.id.transitionId);if(!p)throw new InvariantError("prepare_missing","prepare required");return p}
}