import { cmd, digest, identity, InvariantError, Journal, type Id, type O, type Receipt } from "../e01/kernel.ts";
export const DOMAIN="session.snapshot";
export class SessionSnapshotV2Runtime{readonly journal:Journal;readonly runId:string;readonly sessionId:string;constructor(journal:Journal,runId:string,sessionId:string){this.journal=journal;this.runId=runId;this.sessionId=sessionId} operations(){return ["bootstrap","validate","normalize","reserve","prepare","start","observe","merge","checkpoint","suspend","resume","cancel","timeout","quarantine","retry","reconcile","compact","restore","settle","commit","acknowledge","project","finalize","audit","disable","recover","close","snapshot"]} async dispatch(name:string,payload:O={},id?:Id):Promise<Receipt>{switch(name){
case "bootstrap":return this.bootstrap(payload,id);
case "validate":return this.validate(payload,id);
case "normalize":return this.normalize(payload,id);
case "reserve":return this.reserve(payload,id);
case "prepare":return this.prepare(payload,id);
case "start":return this.start(payload,id);
case "observe":return this.observe(payload,id);
case "merge":return this.merge(payload,id);
case "checkpoint":return this.checkpoint(payload,id);
case "suspend":return this.suspend(payload,id);
case "resume":return this.resume(payload,id);
case "cancel":return this.cancel(payload,id);
case "timeout":return this.timeout(payload,id);
case "quarantine":return this.quarantine(payload,id);
case "retry":return this.retry(payload,id);
case "reconcile":return this.reconcile(payload,id);
case "compact":return this.compact(payload,id);
case "restore":return this.restore(payload,id);
case "settle":return this.settle(payload,id);
case "commit":return this.commit(payload,id);
case "acknowledge":return this.acknowledge(payload,id);
case "project":return this.project(payload,id);
case "finalize":return this.finalize(payload,id);
case "audit":return this.audit(payload,id);
case "disable":return this.disable(payload,id);
case "recover":return this.recover(payload,id);
case "close":return this.close(payload,id);
case "snapshot":return this.snapshot(payload,id);
default:throw new InvariantError("unknown_operation",name)}}
async bootstrap(payload:O={},given?:Id):Promise<Receipt>{
const op="bootstrap";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":bootstrap"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:1,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async validate(payload:O={},given?:Id):Promise<Receipt>{
const op="validate";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":validate"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:2,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async normalize(payload:O={},given?:Id):Promise<Receipt>{
const op="normalize";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":normalize"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:3,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async reserve(payload:O={},given?:Id):Promise<Receipt>{
const op="reserve";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":reserve"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:4,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async prepare(payload:O={},given?:Id):Promise<Receipt>{
const op="prepare";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":prepare"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:5,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async start(payload:O={},given?:Id):Promise<Receipt>{
const op="start";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":start"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,true);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
this.journal.effect(x,{domain:DOMAIN,operation:op,ordinal:6,terminal:true,digest:payloadDigest,audit});
const patch={ [DOMAIN]:{last_operation:op,ordinal:6,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async observe(payload:O={},given?:Id):Promise<Receipt>{
const op="observe";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":observe"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:7,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async merge(payload:O={},given?:Id):Promise<Receipt>{
const op="merge";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":merge"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:8,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async checkpoint(payload:O={},given?:Id):Promise<Receipt>{
const op="checkpoint";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":checkpoint"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:9,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async suspend(payload:O={},given?:Id):Promise<Receipt>{
const op="suspend";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":suspend"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:10,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async resume(payload:O={},given?:Id):Promise<Receipt>{
const op="resume";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":resume"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:11,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async cancel(payload:O={},given?:Id):Promise<Receipt>{
const op="cancel";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":cancel"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:12,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async timeout(payload:O={},given?:Id):Promise<Receipt>{
const op="timeout";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":timeout"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:13,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async quarantine(payload:O={},given?:Id):Promise<Receipt>{
const op="quarantine";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":quarantine"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:14,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async retry(payload:O={},given?:Id):Promise<Receipt>{
const op="retry";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":retry"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,true);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
this.journal.effect(x,{domain:DOMAIN,operation:op,ordinal:15,terminal:true,digest:payloadDigest,audit});
const patch={ [DOMAIN]:{last_operation:op,ordinal:15,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async reconcile(payload:O={},given?:Id):Promise<Receipt>{
const op="reconcile";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":reconcile"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:16,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async compact(payload:O={},given?:Id):Promise<Receipt>{
const op="compact";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":compact"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:17,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async restore(payload:O={},given?:Id):Promise<Receipt>{
const op="restore";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":restore"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:18,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async settle(payload:O={},given?:Id):Promise<Receipt>{
const op="settle";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":settle"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,true);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
this.journal.effect(x,{domain:DOMAIN,operation:op,ordinal:19,terminal:true,digest:payloadDigest,audit});
const patch={ [DOMAIN]:{last_operation:op,ordinal:19,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async commit(payload:O={},given?:Id):Promise<Receipt>{
const op="commit";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":commit"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:20,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async acknowledge(payload:O={},given?:Id):Promise<Receipt>{
const op="acknowledge";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":acknowledge"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:21,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async project(payload:O={},given?:Id):Promise<Receipt>{
const op="project";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":project"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,true);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
this.journal.effect(x,{domain:DOMAIN,operation:op,ordinal:22,terminal:true,digest:payloadDigest,audit});
const patch={ [DOMAIN]:{last_operation:op,ordinal:22,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async finalize(payload:O={},given?:Id):Promise<Receipt>{
const op="finalize";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":finalize"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:23,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async audit(payload:O={},given?:Id):Promise<Receipt>{
const op="audit";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":audit"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:24,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async disable(payload:O={},given?:Id):Promise<Receipt>{
const op="disable";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":disable"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:25,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async recover(payload:O={},given?:Id):Promise<Receipt>{
const op="recover";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":recover"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:26,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async close(payload:O={},given?:Id):Promise<Receipt>{
const op="close";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":close"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,true);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
this.journal.effect(x,{domain:DOMAIN,operation:op,ordinal:27,terminal:true,digest:payloadDigest,audit});
const patch={ [DOMAIN]:{last_operation:op,ordinal:27,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
async snapshot(payload:O={},given?:Id):Promise<Receipt>{
const op="snapshot";
const id=given||identity(this.runId,this.sessionId,DOMAIN+":snapshot"+digest(payload).slice(7,19),this.journal.revision);
const payloadDigest=digest(payload);
const payloadKeys=Object.keys(payload).sort();
const revisionBefore=this.journal.revision;
const stateBefore=this.journal.state;
const stateDigestBefore=digest(stateBefore);
if(!id.runId||!id.sessionId)throw new InvariantError("scope_missing",DOMAIN+" requires run and session scope");
if(id.expectedRevision!==revisionBefore)throw new InvariantError("stale_revision",DOMAIN+" observed stale revision");
if(payload.owner==="python"||payload.logical_owner==="python")throw new InvariantError("stale_owner",DOMAIN+" rejects Python logical owner");
const operationKey=DOMAIN+":"+op;
const audit={operation_key:operationKey,payload_keys:payloadKeys,payload_digest:payloadDigest,state_digest_before:stateDigestBefore,revision_before:revisionBefore} as O;
const normalized={...payload,audit,canonical_owner:"typescript",operation_key:operationKey} as O;
const x=cmd(DOMAIN,op,id,normalized,false);
if(x.readSet.length===0||x.writeSet.length===0)throw new InvariantError("access_set_missing",operationKey);
const p=this.journal.prepare(x);
if(p.status==="acked")return p;
const patch={ [DOMAIN]:{last_operation:op,ordinal:28,payload_digest:payloadDigest,transition_id:id.transitionId,revision:revisionBefore+1,audit}} as O;
const event={domain:DOMAIN,phase:op,transition_id:id.transitionId,canonical_owner:"typescript",operation_key:operationKey,payload_digest:payloadDigest} as O;
const r=this.journal.commit(x,patch,[event]);
if(r.after!==revisionBefore+1)throw new InvariantError("revision_commit_mismatch",operationKey);
return this.journal.ack(r.id.transitionId)}
}
