import assert from "node:assert/strict";
import { test } from "bun:test";

import {
  McpCapabilityCatalog,
  McpInstructionRuntime,
  McpPromptProjection,
  McpResourceProjection,
  McpSseParser,
  McpToolProjection,
} from "../../src/index.ts";

interface McpMatrixCase {
  id: string;
  serverId: string;
  epoch: number;
  readOnly: boolean;
  requiredArgument: boolean;
  notificationMethod: string;
  invalidatedKind: "tool" | "resource" | "prompt";
  removeAfter: boolean;
  instructionSuffix: string;
  templateValue: string;
}

const cases: McpMatrixCase[] = [
  {
    id: "mcp-001",
    serverId: "peer-1-mcp-001",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-1",
    templateValue: "segment 1",
  },
  {
    id: "mcp-002",
    serverId: "peer-2-mcp-002",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 2",
  },
  {
    id: "mcp-003",
    serverId: "peer-3-mcp-003",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 3",
  },
  {
    id: "mcp-004",
    serverId: "peer-4-mcp-004",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 4",
  },
  {
    id: "mcp-005",
    serverId: "peer-5-mcp-005",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 5",
  },
  {
    id: "mcp-006",
    serverId: "peer-6-mcp-006",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-6",
    templateValue: "segment 6",
  },
  {
    id: "mcp-007",
    serverId: "peer-7-mcp-007",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 7",
  },
  {
    id: "mcp-008",
    serverId: "peer-1-mcp-008",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 8",
  },
  {
    id: "mcp-009",
    serverId: "peer-2-mcp-009",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 9",
  },
  {
    id: "mcp-010",
    serverId: "peer-3-mcp-010",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 10",
  },
  {
    id: "mcp-011",
    serverId: "peer-4-mcp-011",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: true,
    instructionSuffix: "policy-11",
    templateValue: "segment 11",
  },
  {
    id: "mcp-012",
    serverId: "peer-5-mcp-012",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 12",
  },
  {
    id: "mcp-013",
    serverId: "peer-6-mcp-013",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 13",
  },
  {
    id: "mcp-014",
    serverId: "peer-7-mcp-014",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 14",
  },
  {
    id: "mcp-015",
    serverId: "peer-1-mcp-015",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 15",
  },
  {
    id: "mcp-016",
    serverId: "peer-2-mcp-016",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-5",
    templateValue: "segment 16",
  },
  {
    id: "mcp-017",
    serverId: "peer-3-mcp-017",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 17",
  },
  {
    id: "mcp-018",
    serverId: "peer-4-mcp-018",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 18",
  },
  {
    id: "mcp-019",
    serverId: "peer-5-mcp-019",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 19",
  },
  {
    id: "mcp-020",
    serverId: "peer-6-mcp-020",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 20",
  },
  {
    id: "mcp-021",
    serverId: "peer-7-mcp-021",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-10",
    templateValue: "segment 21",
  },
  {
    id: "mcp-022",
    serverId: "peer-1-mcp-022",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 22",
  },
  {
    id: "mcp-023",
    serverId: "peer-2-mcp-023",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 23",
  },
  {
    id: "mcp-024",
    serverId: "peer-3-mcp-024",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 24",
  },
  {
    id: "mcp-025",
    serverId: "peer-4-mcp-025",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 25",
  },
  {
    id: "mcp-026",
    serverId: "peer-5-mcp-026",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: true,
    instructionSuffix: "policy-4",
    templateValue: "segment 26",
  },
  {
    id: "mcp-027",
    serverId: "peer-6-mcp-027",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 27",
  },
  {
    id: "mcp-028",
    serverId: "peer-7-mcp-028",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 28",
  },
  {
    id: "mcp-029",
    serverId: "peer-1-mcp-029",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 29",
  },
  {
    id: "mcp-030",
    serverId: "peer-2-mcp-030",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 30",
  },
  {
    id: "mcp-031",
    serverId: "peer-3-mcp-031",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-9",
    templateValue: "segment 31",
  },
  {
    id: "mcp-032",
    serverId: "peer-4-mcp-032",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 32",
  },
  {
    id: "mcp-033",
    serverId: "peer-5-mcp-033",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 33",
  },
  {
    id: "mcp-034",
    serverId: "peer-6-mcp-034",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 34",
  },
  {
    id: "mcp-035",
    serverId: "peer-7-mcp-035",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 35",
  },
  {
    id: "mcp-036",
    serverId: "peer-1-mcp-036",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-3",
    templateValue: "segment 36",
  },
  {
    id: "mcp-037",
    serverId: "peer-2-mcp-037",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 37",
  },
  {
    id: "mcp-038",
    serverId: "peer-3-mcp-038",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 38",
  },
  {
    id: "mcp-039",
    serverId: "peer-4-mcp-039",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 39",
  },
  {
    id: "mcp-040",
    serverId: "peer-5-mcp-040",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 40",
  },
  {
    id: "mcp-041",
    serverId: "peer-6-mcp-041",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: true,
    instructionSuffix: "policy-8",
    templateValue: "segment 41",
  },
  {
    id: "mcp-042",
    serverId: "peer-7-mcp-042",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 42",
  },
  {
    id: "mcp-043",
    serverId: "peer-1-mcp-043",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 43",
  },
  {
    id: "mcp-044",
    serverId: "peer-2-mcp-044",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 44",
  },
  {
    id: "mcp-045",
    serverId: "peer-3-mcp-045",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 45",
  },
  {
    id: "mcp-046",
    serverId: "peer-4-mcp-046",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-2",
    templateValue: "segment 46",
  },
  {
    id: "mcp-047",
    serverId: "peer-5-mcp-047",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 47",
  },
  {
    id: "mcp-048",
    serverId: "peer-6-mcp-048",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 48",
  },
  {
    id: "mcp-049",
    serverId: "peer-7-mcp-049",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 49",
  },
  {
    id: "mcp-050",
    serverId: "peer-1-mcp-050",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 50",
  },
  {
    id: "mcp-051",
    serverId: "peer-2-mcp-051",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-7",
    templateValue: "segment 51",
  },
  {
    id: "mcp-052",
    serverId: "peer-3-mcp-052",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 52",
  },
  {
    id: "mcp-053",
    serverId: "peer-4-mcp-053",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 53",
  },
  {
    id: "mcp-054",
    serverId: "peer-5-mcp-054",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 54",
  },
  {
    id: "mcp-055",
    serverId: "peer-6-mcp-055",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 55",
  },
  {
    id: "mcp-056",
    serverId: "peer-7-mcp-056",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: true,
    instructionSuffix: "policy-1",
    templateValue: "segment 56",
  },
  {
    id: "mcp-057",
    serverId: "peer-1-mcp-057",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 57",
  },
  {
    id: "mcp-058",
    serverId: "peer-2-mcp-058",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 58",
  },
  {
    id: "mcp-059",
    serverId: "peer-3-mcp-059",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 59",
  },
  {
    id: "mcp-060",
    serverId: "peer-4-mcp-060",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 60",
  },
  {
    id: "mcp-061",
    serverId: "peer-5-mcp-061",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-6",
    templateValue: "segment 61",
  },
  {
    id: "mcp-062",
    serverId: "peer-6-mcp-062",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 62",
  },
  {
    id: "mcp-063",
    serverId: "peer-7-mcp-063",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 63",
  },
  {
    id: "mcp-064",
    serverId: "peer-1-mcp-064",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 64",
  },
  {
    id: "mcp-065",
    serverId: "peer-2-mcp-065",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 65",
  },
  {
    id: "mcp-066",
    serverId: "peer-3-mcp-066",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-11",
    templateValue: "segment 66",
  },
  {
    id: "mcp-067",
    serverId: "peer-4-mcp-067",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 67",
  },
  {
    id: "mcp-068",
    serverId: "peer-5-mcp-068",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 68",
  },
  {
    id: "mcp-069",
    serverId: "peer-6-mcp-069",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 69",
  },
  {
    id: "mcp-070",
    serverId: "peer-7-mcp-070",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 70",
  },
  {
    id: "mcp-071",
    serverId: "peer-1-mcp-071",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: true,
    instructionSuffix: "policy-5",
    templateValue: "segment 71",
  },
  {
    id: "mcp-072",
    serverId: "peer-2-mcp-072",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 72",
  },
  {
    id: "mcp-073",
    serverId: "peer-3-mcp-073",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 73",
  },
  {
    id: "mcp-074",
    serverId: "peer-4-mcp-074",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 74",
  },
  {
    id: "mcp-075",
    serverId: "peer-5-mcp-075",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 75",
  },
  {
    id: "mcp-076",
    serverId: "peer-6-mcp-076",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-10",
    templateValue: "segment 76",
  },
  {
    id: "mcp-077",
    serverId: "peer-7-mcp-077",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 77",
  },
  {
    id: "mcp-078",
    serverId: "peer-1-mcp-078",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 78",
  },
  {
    id: "mcp-079",
    serverId: "peer-2-mcp-079",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 79",
  },
  {
    id: "mcp-080",
    serverId: "peer-3-mcp-080",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-3",
    templateValue: "segment 80",
  },
  {
    id: "mcp-081",
    serverId: "peer-4-mcp-081",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-4",
    templateValue: "segment 81",
  },
  {
    id: "mcp-082",
    serverId: "peer-5-mcp-082",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 82",
  },
  {
    id: "mcp-083",
    serverId: "peer-6-mcp-083",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 83",
  },
  {
    id: "mcp-084",
    serverId: "peer-7-mcp-084",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 84",
  },
  {
    id: "mcp-085",
    serverId: "peer-1-mcp-085",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-8",
    templateValue: "segment 85",
  },
  {
    id: "mcp-086",
    serverId: "peer-2-mcp-086",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: true,
    instructionSuffix: "policy-9",
    templateValue: "segment 86",
  },
  {
    id: "mcp-087",
    serverId: "peer-3-mcp-087",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 87",
  },
  {
    id: "mcp-088",
    serverId: "peer-4-mcp-088",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 88",
  },
  {
    id: "mcp-089",
    serverId: "peer-5-mcp-089",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 89",
  },
  {
    id: "mcp-090",
    serverId: "peer-6-mcp-090",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-2",
    templateValue: "segment 90",
  },
  {
    id: "mcp-091",
    serverId: "peer-7-mcp-091",
    epoch: 3,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: true,
    instructionSuffix: "policy-3",
    templateValue: "segment 91",
  },
  {
    id: "mcp-092",
    serverId: "peer-1-mcp-092",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-4",
    templateValue: "segment 92",
  },
  {
    id: "mcp-093",
    serverId: "peer-2-mcp-093",
    epoch: 1,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-5",
    templateValue: "segment 93",
  },
  {
    id: "mcp-094",
    serverId: "peer-3-mcp-094",
    epoch: 2,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-6",
    templateValue: "segment 94",
  },
  {
    id: "mcp-095",
    serverId: "peer-4-mcp-095",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-7",
    templateValue: "segment 95",
  },
  {
    id: "mcp-096",
    serverId: "peer-5-mcp-096",
    epoch: 4,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: true,
    instructionSuffix: "policy-8",
    templateValue: "segment 96",
  },
  {
    id: "mcp-097",
    serverId: "peer-6-mcp-097",
    epoch: 1,
    readOnly: true,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-9",
    templateValue: "segment 97",
  },
  {
    id: "mcp-098",
    serverId: "peer-7-mcp-098",
    epoch: 2,
    readOnly: false,
    requiredArgument: true,
    notificationMethod: "notifications/resources/list_changed",
    invalidatedKind: "resource",
    removeAfter: false,
    instructionSuffix: "policy-10",
    templateValue: "segment 98",
  },
  {
    id: "mcp-099",
    serverId: "peer-1-mcp-099",
    epoch: 3,
    readOnly: true,
    requiredArgument: true,
    notificationMethod: "notifications/prompts/list_changed",
    invalidatedKind: "prompt",
    removeAfter: false,
    instructionSuffix: "policy-11",
    templateValue: "segment 99",
  },
  {
    id: "mcp-100",
    serverId: "peer-2-mcp-100",
    epoch: 4,
    readOnly: false,
    requiredArgument: false,
    notificationMethod: "notifications/tools/list_changed",
    invalidatedKind: "tool",
    removeAfter: false,
    instructionSuffix: "policy-1",
    templateValue: "segment 100",
  },
  // __MCP_MATRIX_CASES__
];

for (const value of cases) {
  test(`MCP matrix ${value.id} owns catalog, projections, instructions, SSE, and restore`, () => {
    let tick = 0;
    const now = () => new Date(1_783_900_000_000 + tick++ * 1_000);
    const catalog = new McpCapabilityCatalog({ now });
    const connectionId = `connection-${value.id}`;
    const toolName = `tool_${value.id.replaceAll("-", "_")}`;
    const resourceUri = `memo://${value.serverId}/${value.id}`;
    const templateUri = `memo://${value.serverId}/items/{segment}`;
    const promptName = `prompt_${value.id.replaceAll("-", "_")}`;
    const diff = catalog.applySnapshot({
      serverId: value.serverId,
      connectionId,
      connectionEpoch: value.epoch,
      initialize: {
        protocolVersion: "2025-06-18",
        capabilities: {
          experimental: {},
          logging: {},
          completions: {},
          prompts: { listChanged: true },
          resources: { subscribe: true, listChanged: true },
          tools: { listChanged: true },
          tasks: { list: true, cancel: true, requests: {} },
        },
        serverInfo: {
          name: `server-${value.id}`,
          title: `Server ${value.id}`,
          version: "1.0.0",
          websiteUrl: null,
          icons: [],
        },
        instructions: `Instruction ${value.instructionSuffix}`,
        meta: { matrix_id: value.id },
      },
      tools: [{
        name: toolName,
        title: `Tool ${value.id}`,
        description: `Execute ${value.id}`,
        inputSchema: {
          type: "object",
          properties: { value: { type: "string" } },
          required: value.requiredArgument ? ["value"] : [],
          additionalProperties: false,
        },
        outputSchema: {
          type: "object",
          properties: { ok: { type: "boolean" } },
        },
        annotations: {
          title: `Tool ${value.id}`,
          readOnlyHint: value.readOnly,
          destructiveHint: !value.readOnly,
          idempotentHint: value.readOnly,
          openWorldHint: !value.readOnly,
        },
        icons: [],
        meta: { matrix_id: value.id },
      }],
      resources: [{
        uri: resourceUri,
        name: `resource-${value.id}`,
        title: `Resource ${value.id}`,
        description: `Resource for ${value.id}`,
        mimeType: "application/json",
        size: 128 + value.id.length,
        annotations: {
          audience: ["assistant"],
          priority: 0.5,
          lastModified: "2026-07-17T00:00:00.000Z",
        },
        icons: [],
        meta: { matrix_id: value.id },
      }],
      resourceTemplates: [{
        uriTemplate: templateUri,
        name: `template-${value.id}`,
        title: `Template ${value.id}`,
        description: `Template for ${value.id}`,
        mimeType: "application/json",
        annotations: {
          audience: ["assistant"],
          priority: 0.7,
          lastModified: null,
        },
        icons: [],
        meta: { matrix_id: value.id },
      }],
      prompts: [{
        name: promptName,
        title: `Prompt ${value.id}`,
        description: `Prompt for ${value.id}`,
        arguments: [{
          name: "subject",
          title: "Subject",
          description: "Prompt subject",
          required: value.requiredArgument,
        }],
        icons: [],
        meta: { matrix_id: value.id },
      }],
      expectedRevision: undefined,
      metadata: { matrix_id: value.id },
    });
    assert.equal(diff.priorRevision, 0);
    assert.equal(diff.revision, 1);
    assert.deepEqual(diff.added.tool, [toolName]);
    assert.deepEqual(diff.added.resource, [resourceUri]);
    assert.deepEqual(diff.added.prompt, [promptName]);

    const server = catalog.require(value.serverId);
    const projectedTools = new McpToolProjection({
      prefix: "mcp",
      includeServerInstructions: true,
      collisionPolicy: "digest_suffix",
    }).materialize(server);
    assert.equal(projectedTools.length, 1);
    assert.equal(projectedTools[0]?.originalName, toolName);
    assert.equal(projectedTools[0]?.readOnly, value.readOnly);
    assert.equal(projectedTools[0]?.destructive, !value.readOnly);
    assert.match(projectedTools[0]?.description ?? "", /Instruction/);

    const resourceProjection = new McpResourceProjection();
    const projectedResources = resourceProjection.materialize(server);
    assert.equal(projectedResources.resources[0]?.uri, resourceUri);
    assert.equal(projectedResources.templates[0]?.variables[0], "segment");
    const resolvedUri = resourceProjection.resolveTemplate(
      projectedResources.templates[0]!,
      { segment: value.templateValue },
    );
    assert.equal(resolvedUri, templateUri.replace("{segment}", encodeURIComponent(value.templateValue)));

    const promptProjection = new McpPromptProjection({ namespace: "mcp" });
    const projectedPrompt = promptProjection.materialize(server)[0]!;
    const promptArguments = promptProjection.validateArguments(
      projectedPrompt,
      value.requiredArgument ? { subject: value.id } : {},
    );
    assert.equal(promptArguments.subject, value.requiredArgument ? value.id : undefined);

    const instructions = new McpInstructionRuntime({ now });
    const instructionDelta = instructions.applyDelta({
      serverId: value.serverId,
      connectionId,
      connectionEpoch: value.epoch,
      catalogRevision: server.revision,
      instructions: server.instructions,
      metadata: { matrix_id: value.id },
    });
    assert.equal(instructionDelta.operation, "add");
    assert.equal(instructions.compose([value.serverId]).servers[0], value.serverId);
    const restoredInstructions = new McpInstructionRuntime({ now, snapshot: instructions.snapshot() });
    assert.equal(restoredInstructions.get(value.serverId)?.digest, instructionDelta.digest);

    const invalidated = catalog.applyNotification({
      serverId: value.serverId,
      connectionId,
      connectionEpoch: value.epoch,
      method: value.notificationMethod,
      params: { reason: value.id },
      observedAt: now().toISOString(),
      metadata: { matrix_id: value.id },
    });
    assert.deepEqual(invalidated.invalidated, [value.invalidatedKind]);
    assert.ok(catalog.require(value.serverId).invalidatedKinds.includes(value.invalidatedKind));

    const restoredCatalog = new McpCapabilityCatalog({ now, snapshot: catalog.snapshot() });
    assert.equal(restoredCatalog.require(value.serverId).digest, catalog.require(value.serverId).digest);
    assert.equal(restoredCatalog.findTool(value.serverId, toolName)?.name, toolName);

    const parser = new McpSseParser({ now, maximumDataLines: 8 });
    assert.deepEqual(parser.push(`id: ${value.id}\nevent: message\nretry: 1500\n`), []);
    const resumedParser = new McpSseParser({ now }, parser.snapshot());
    const events = resumedParser.push(`data: {"matrix":"${value.id}"}\n\n`);
    assert.equal(events.length, 1);
    assert.equal(events[0]?.eventId, value.id);
    assert.equal(events[0]?.event, "message");
    assert.equal(JSON.parse(events[0]?.data ?? "{}").matrix, value.id);
    assert.equal(events[0]?.retryMs, 1500);

    if (value.removeAfter) {
      const removed = restoredCatalog.remove(value.serverId, `matrix-${value.id}`);
      assert.equal(removed?.kind, "server_removed");
      assert.equal(restoredCatalog.get(value.serverId), null);
    } else {
      assert.equal(restoredCatalog.get(value.serverId)?.serverId, value.serverId);
    }
  });
}
