from __future__ import annotations

from collections.abc import Mapping
from typing import Any


RECOVERY_BY_CODE: dict[str, str] = {
    "loopx_package_lock_missing": (
        "Restore config/loopx/package-lock.json from the pinned Zyra release."
    ),
    "loopx_package_lock_invalid": (
        "Replace the package lock with the copy from the same Zyra release."
    ),
    "loopx_artifact_missing": (
        "Restore the complete LoopX offline artifacts from the Zyra release bundle."
    ),
    "loopx_artifact_tampered": (
        "Discard this bundle and reinstall from a checksum-verified Zyra release."
    ),
    "loopx_source_manifest_mismatch": (
        "Rebuild the pinned bundle from the exact approved LoopX source commit."
    ),
    "loopx_python_incompatible": (
        "Use CPython 3.11 or newer and rerun the project-local installer."
    ),
    "loopx_dependency_missing": (
        "Install the locked dependency into the selected interpreter; do not use the network during release installation."
    ),
    "loopx_profile_unsupported": (
        "Select the Windows/release wheel profile or run the Linux/WSL profile on a supported host."
    ),
    "loopx_workspace_unwritable": (
        "Choose a writable project workspace; do not fall back to a user-home install."
    ),
    "loopx_partial_install": (
        "Remove only the reported incomplete project-local install directory, then rerun the installer."
    ),
    "loopx_upgrade_required": (
        "Run a separately reviewed pinned-version upgrade; in-place overwrite is blocked."
    ),
    "loopx_installed_file_tampered": (
        "Replace the project-local LoopX install from the verified offline artifact."
    ),
    "loopx_import_failed": (
        "Reinstall from the verified wheel and confirm the selected interpreter can read the project-local site-packages directory."
    ),
    "loopx_cli_entry_failed": (
        "Reinstall the pinned package and use the project-local CLI entry generated by Zyra."
    ),
    "loopx_user_write_forbidden": (
        "Use the project-local install profile; user home, shell profile, global skill and system PATH writes are disabled."
    ),
}


class LoopXInstallError(RuntimeError):
    """Fail-closed LoopX package, installation, or doctor error."""

    def __init__(
        self,
        message: str,
        *,
        code: str,
        details: Mapping[str, Any] | None = None,
        retryable: bool = False,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.code = code
        self.details = dict(details or {})
        self.retryable = retryable

    @property
    def recovery(self) -> str:
        return RECOVERY_BY_CODE.get(
            self.code,
            "Inspect the LoopX doctor receipt and restore the matching pinned release.",
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": "zyra.loopx-install-error/v1",
            "code": self.code,
            "message": self.message,
            "retryable": self.retryable,
            "recovery": self.recovery,
            "details": self.details,
        }


__all__ = ["LoopXInstallError", "RECOVERY_BY_CODE"]
