import assert from "node:assert/strict";
import { test } from "bun:test";

import { E02ProjectionRuntime, type E02ProjectionDomain, type E02RuntimeIdentity } from "../../src/e02/index.ts";

interface ProjectionCase {
  id: string;
  domain: E02ProjectionDomain;
  secretKey: string;
  includeHistory: boolean;
  includePayloads: boolean;
  maximumStringLength: number;
}

const runtime: E02RuntimeIdentity = {
  runtimeId: "projection-matrix-runtime",
  runId: "projection-matrix-run",
  taskId: "projection-matrix-task",
  sessionId: "projection-matrix-session",
  workerRequestId: "projection-matrix-worker",
  epoch: 1,
};

const cases: ProjectionCase[] = [
  {
    id: "projection-001",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: true,
    maximumStringLength: 32,
  },
  {
    id: "projection-002",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 33,
  },
  {
    id: "projection-003",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 34,
  },
  {
    id: "projection-004",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 35,
  },
  {
    id: "projection-005",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 36,
  },
  {
    id: "projection-006",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 37,
  },
  {
    id: "projection-007",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 38,
  },
  {
    id: "projection-008",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 39,
  },
  {
    id: "projection-009",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 40,
  },
  {
    id: "projection-010",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 41,
  },
  {
    id: "projection-011",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 42,
  },
  {
    id: "projection-012",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 43,
  },
  {
    id: "projection-013",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 44,
  },
  {
    id: "projection-014",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 45,
  },
  {
    id: "projection-015",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 46,
  },
  {
    id: "projection-016",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 47,
  },
  {
    id: "projection-017",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 48,
  },
  {
    id: "projection-018",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 49,
  },
  {
    id: "projection-019",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 50,
  },
  {
    id: "projection-020",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 51,
  },
  {
    id: "projection-021",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: true,
    maximumStringLength: 52,
  },
  {
    id: "projection-022",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 53,
  },
  {
    id: "projection-023",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 54,
  },
  {
    id: "projection-024",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 55,
  },
  {
    id: "projection-025",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 32,
  },
  {
    id: "projection-026",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 33,
  },
  {
    id: "projection-027",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 34,
  },
  {
    id: "projection-028",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 35,
  },
  {
    id: "projection-029",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 36,
  },
  {
    id: "projection-030",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 37,
  },
  {
    id: "projection-031",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 38,
  },
  {
    id: "projection-032",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 39,
  },
  {
    id: "projection-033",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 40,
  },
  {
    id: "projection-034",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 41,
  },
  {
    id: "projection-035",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 42,
  },
  {
    id: "projection-036",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 43,
  },
  {
    id: "projection-037",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 44,
  },
  {
    id: "projection-038",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 45,
  },
  {
    id: "projection-039",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 46,
  },
  {
    id: "projection-040",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 47,
  },
  {
    id: "projection-041",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: true,
    maximumStringLength: 48,
  },
  {
    id: "projection-042",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 49,
  },
  {
    id: "projection-043",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 50,
  },
  {
    id: "projection-044",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 51,
  },
  {
    id: "projection-045",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 52,
  },
  {
    id: "projection-046",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 53,
  },
  {
    id: "projection-047",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 54,
  },
  {
    id: "projection-048",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 55,
  },
  {
    id: "projection-049",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 32,
  },
  {
    id: "projection-050",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 33,
  },
  {
    id: "projection-051",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 34,
  },
  {
    id: "projection-052",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 35,
  },
  {
    id: "projection-053",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 36,
  },
  {
    id: "projection-054",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 37,
  },
  {
    id: "projection-055",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 38,
  },
  {
    id: "projection-056",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 39,
  },
  {
    id: "projection-057",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 40,
  },
  {
    id: "projection-058",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 41,
  },
  {
    id: "projection-059",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 42,
  },
  {
    id: "projection-060",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 43,
  },
  {
    id: "projection-061",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: true,
    maximumStringLength: 44,
  },
  {
    id: "projection-062",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 45,
  },
  {
    id: "projection-063",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 46,
  },
  {
    id: "projection-064",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 47,
  },
  {
    id: "projection-065",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 48,
  },
  {
    id: "projection-066",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 49,
  },
  {
    id: "projection-067",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 50,
  },
  {
    id: "projection-068",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 51,
  },
  {
    id: "projection-069",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 52,
  },
  {
    id: "projection-070",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 53,
  },
  {
    id: "projection-071",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 54,
  },
  {
    id: "projection-072",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 55,
  },
  {
    id: "projection-073",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 32,
  },
  {
    id: "projection-074",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 33,
  },
  {
    id: "projection-075",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 34,
  },
  {
    id: "projection-076",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 35,
  },
  {
    id: "projection-077",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 36,
  },
  {
    id: "projection-078",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 37,
  },
  {
    id: "projection-079",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 38,
  },
  {
    id: "projection-080",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 39,
  },
  {
    id: "projection-081",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: true,
    maximumStringLength: 40,
  },
  {
    id: "projection-082",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 41,
  },
  {
    id: "projection-083",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 42,
  },
  {
    id: "projection-084",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 43,
  },
  {
    id: "projection-085",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 44,
  },
  {
    id: "projection-086",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 45,
  },
  {
    id: "projection-087",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 46,
  },
  {
    id: "projection-088",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 47,
  },
  {
    id: "projection-089",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 48,
  },
  {
    id: "projection-090",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 49,
  },
  {
    id: "projection-091",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 50,
  },
  {
    id: "projection-092",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 51,
  },
  {
    id: "projection-093",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 52,
  },
  {
    id: "projection-094",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 53,
  },
  {
    id: "projection-095",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 54,
  },
  {
    id: "projection-096",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 55,
  },
  {
    id: "projection-097",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 32,
  },
  {
    id: "projection-098",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 33,
  },
  {
    id: "projection-099",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 34,
  },
  {
    id: "projection-100",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 35,
  },
  {
    id: "projection-101",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: true,
    maximumStringLength: 36,
  },
  {
    id: "projection-102",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 37,
  },
  {
    id: "projection-103",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 38,
  },
  {
    id: "projection-104",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 39,
  },
  {
    id: "projection-105",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 40,
  },
  {
    id: "projection-106",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 41,
  },
  {
    id: "projection-107",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 42,
  },
  {
    id: "projection-108",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 43,
  },
  {
    id: "projection-109",
    domain: "runtime",
    secretKey: "access_token",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 44,
  },
  {
    id: "projection-110",
    domain: "permission",
    secretKey: "refresh_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 45,
  },
  {
    id: "projection-111",
    domain: "mcp",
    secretKey: "authorization",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 46,
  },
  {
    id: "projection-112",
    domain: "skill",
    secretKey: "cookie",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 47,
  },
  {
    id: "projection-113",
    domain: "plugin",
    secretKey: "password",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 48,
  },
  {
    id: "projection-114",
    domain: "command",
    secretKey: "secret",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 49,
  },
  {
    id: "projection-115",
    domain: "agent",
    secretKey: "token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 50,
  },
  {
    id: "projection-116",
    domain: "route",
    secretKey: "api_key",
    includeHistory: false,
    includePayloads: true,
    maximumStringLength: 51,
  },
  {
    id: "projection-117",
    domain: "checkpoint",
    secretKey: "apikey",
    includeHistory: true,
    includePayloads: false,
    maximumStringLength: 52,
  },
  {
    id: "projection-118",
    domain: "execution",
    secretKey: "private_key",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 53,
  },
  {
    id: "projection-119",
    domain: "recovery",
    secretKey: "credential",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 54,
  },
  {
    id: "projection-120",
    domain: "event",
    secretKey: "session_token",
    includeHistory: false,
    includePayloads: false,
    maximumStringLength: 55,
  },
  // __PROJECTION_CASES__
];

for (const value of cases) {
  test(`projection matrix ${value.id} redacts, truncates, filters, pages, and diffs`, () => {
    const projections = new E02ProjectionRuntime({ runtime });
    const initialDomain = {
      status: "open",
      [value.secretKey]: `secret-${value.id}`,
      payload: { private_value: `private-${value.id}` },
      history: [{ revision: 1, value: value.id }],
      message: `message-${value.id}-${"x".repeat(128)}`,
      count: 1,
    };
    const firstSource = {
      snapshotHash: `sha256:first-${value.id}`,
      snapshotSequence: 1,
      [value.domain]: initialDomain,
    };
    const first = projections.capture(firstSource, {
      domains: [value.domain],
      includeHistory: value.includeHistory,
      includePayloads: value.includePayloads,
      maximumStringLength: value.maximumStringLength,
      maximumArrayItems: 8,
      maximumDepth: 8,
    });
    const rendered = JSON.stringify(first.value);
    assert.doesNotMatch(rendered, new RegExp(`secret-${value.id}`));
    if (!value.includePayloads) assert.doesNotMatch(rendered, new RegExp(`private-${value.id}`));
    if (!value.includeHistory) assert.match(rendered, /history_excluded/);
    assert.ok(first.redactionCount >= 1);
    assert.ok(first.truncationCount >= 1);
    assert.equal(projections.verifyRecord(first.projectionId).ok, true);
    const firstPage = projections.pageRecord(first.projectionId, 3);
    assert.ok(firstPage.items.length > 0);
    assert.equal(firstPage.projectionId, first.projectionId);
    const second = projections.capture({
      ...firstSource,
      snapshotHash: `sha256:second-${value.id}`,
      snapshotSequence: 2,
      [value.domain]: {
        ...initialDomain,
        count: 2,
        added: value.id,
      },
    }, {
      domains: [value.domain],
      includeHistory: value.includeHistory,
      includePayloads: value.includePayloads,
      maximumStringLength: value.maximumStringLength,
      maximumArrayItems: 8,
      maximumDepth: 8,
    });
    const difference = projections.diff(first.projectionId, second.projectionId);
    assert.ok(difference.changedPaths.some((path) => path.endsWith(".count")));
    assert.ok(difference.addedPaths.some((path) => path.endsWith(".added")));
    const subscription = projections.subscribe(`consumer-${value.id}`, [value.domain]);
    assert.equal(projections.pendingForSubscription(subscription.subscriptionId).length, 2);
    const acknowledged = projections.acknowledge(subscription.subscriptionId, second.projectionId);
    assert.equal(acknowledged.lastAcknowledgedSequence, second.sequence);
    assert.equal(projections.pendingForSubscription(subscription.subscriptionId).length, 0);
    assert.equal(projections.health().python_projection_fallback, false);
  });
}
