import assert from "node:assert/strict";
import { test } from "bun:test";

import { E02RecoveryRuntime, type E02RecoverySeverity, type E02RecoverySource, type E02RuntimeIdentity } from "../../src/e02/index.ts";

interface RecoveryCase {
  id: string;
  source: E02RecoverySource;
  sourcePhase: string;
  severity: E02RecoverySeverity;
  idempotent: boolean;
  receiptRecorded: boolean;
}

const runtime: E02RuntimeIdentity = {
  runtimeId: "recovery-matrix-runtime",
  runId: "recovery-matrix-run",
  taskId: "recovery-matrix-task",
  sessionId: "recovery-matrix-session",
  workerRequestId: "recovery-matrix-worker",
  epoch: 1,
};

const cases: RecoveryCase[] = [
  {
    id: "recovery-001",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-002",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-003",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-004",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-005",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-006",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-007",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-008",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-009",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-010",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-011",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-012",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-013",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-014",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-015",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-016",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-017",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-018",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-019",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-020",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-021",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-022",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-023",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-024",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-025",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-026",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-027",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-028",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-029",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-030",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-031",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-032",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-033",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-034",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-035",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-036",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-037",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-038",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-039",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-040",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-041",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-042",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-043",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-044",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-045",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-046",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-047",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-048",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-049",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-050",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-051",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-052",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-053",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-054",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-055",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-056",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-057",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-058",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-059",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-060",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-061",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-062",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-063",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-064",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-065",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-066",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-067",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-068",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-069",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-070",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-071",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-072",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-073",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-074",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-075",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-076",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-077",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-078",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-079",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-080",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-081",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-082",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-083",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-084",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-085",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-086",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-087",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-088",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-089",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-090",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-091",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: true,
    receiptRecorded: true,
  },
  {
    id: "recovery-092",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-093",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-094",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-095",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-096",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: false,
    receiptRecorded: true,
  },
  {
    id: "recovery-097",
    source: "transition",
    sourcePhase: "prepared",
    severity: "low",
    idempotent: true,
    receiptRecorded: false,
  },
  {
    id: "recovery-098",
    source: "execution",
    sourcePhase: "effect_started",
    severity: "medium",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-099",
    source: "checkpoint",
    sourcePhase: "recovery_required",
    severity: "high",
    idempotent: false,
    receiptRecorded: false,
  },
  {
    id: "recovery-100",
    source: "control",
    sourcePhase: "delivery_indeterminate",
    severity: "critical",
    idempotent: true,
    receiptRecorded: false,
  },
  // __RECOVERY_CASES__
];

for (const value of cases) {
  test(`recovery matrix ${value.id} diagnoses and plans without effect replay`, () => {
    const recovery = new E02RecoveryRuntime({ runtime });
    const incident = recovery.observe({
      source: value.source,
      sourceId: `source-${value.id}`,
      sourcePhase: value.sourcePhase,
      summary: `recovery behavior ${value.id}`,
      payload: {
        idempotent: value.idempotent,
        non_idempotent: !value.idempotent,
        effect_started: value.sourcePhase.includes("effect"),
        effect_receipt: value.receiptRecorded ? { ok: true, receipt_id: value.id } : null,
        scenario_id: value.id,
      },
      severity: value.severity,
      metadata: { matrix: true },
    });
    assert.equal(incident.source, value.source);
    assert.equal(incident.severity, value.severity);
    const evidence = recovery.evidenceFor(incident.incidentId);
    assert.equal(evidence.length, 1);
    assert.equal(evidence[0]?.kind, "source_observation");
    const diagnosis = recovery.diagnose(incident.incidentId);
    if (value.receiptRecorded) assert.equal(diagnosis.effectState, "recorded");
    else if (value.sourcePhase === "prepared" || !value.sourcePhase.includes("effect")) {
      assert.equal(diagnosis.effectState, "absent");
    }
    else assert.equal(diagnosis.effectState, "indeterminate");
    const plan = recovery.buildPlan(incident.incidentId);
    assert.ok(plan.steps.length >= 2);
    assert.ok(plan.steps.every((step) => step.reexecutesExternalEffect === false));
    assert.equal(plan.incidentId, incident.incidentId);
    const recommendation = recovery.recommendNext(incident.incidentId);
    assert.equal(recommendation.automatic_effect_replay, false);
    const claim = recovery.claim(incident.incidentId, `owner-${value.id}`);
    assert.equal(claim.incidentId, incident.incidentId);
    const first = plan.steps[0]!;
    const started = recovery.startStep(incident.incidentId, first.stepId, claim.claimId);
    assert.equal(started.status, "running");
    const completed = recovery.completeStep(incident.incidentId, first.stepId, claim.claimId, {
      inspected: true,
      scenario_id: value.id,
    });
    assert.equal(completed.status, "committed");
    assert.ok(recovery.timeline(incident.incidentId).some((entry) => entry.kind === "recovery_step_completed"));
    assert.equal(recovery.verifyIncident(incident.incidentId).ok, true);
    assert.equal(recovery.verifyGraph().ok, true);
    assert.equal(recovery.statistics().steps_reexecuting_external_effects, 0);
    assert.equal(recovery.health().automatic_effect_replay, false);
    assert.equal(recovery.health().scheduler_route_owner, false);
  });
}
