import assert from "node:assert/strict";
import { test } from "bun:test";

import type { ToolSpecContract } from "../../src/contracts.ts";
import { E02RouteRuntime, type E02RouteDomain, type E02RuntimeIdentity } from "../../src/e02/index.ts";

interface RouteCase {
  id: string;
  domain: E02RouteDomain;
  owner: string;
  operation: string;
  priority: number;
}

const runtime: E02RuntimeIdentity = {
  runtimeId: "route-matrix-runtime",
  runId: "route-matrix-run",
  taskId: "route-matrix-task",
  sessionId: "route-matrix-session",
  workerRequestId: "route-matrix-worker",
  epoch: 1,
};

const cases: RouteCase[] = [
  {
    id: "route-001",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 500,
  },
  {
    id: "route-002",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 501,
  },
  {
    id: "route-003",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 502,
  },
  {
    id: "route-004",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 503,
  },
  {
    id: "route-005",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 504,
  },
  {
    id: "route-006",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 505,
  },
  {
    id: "route-007",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 506,
  },
  {
    id: "route-008",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 507,
  },
  {
    id: "route-009",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 508,
  },
  {
    id: "route-010",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 509,
  },
  {
    id: "route-011",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 510,
  },
  {
    id: "route-012",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 511,
  },
  {
    id: "route-013",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 512,
  },
  {
    id: "route-014",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 513,
  },
  {
    id: "route-015",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 514,
  },
  {
    id: "route-016",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 515,
  },
  {
    id: "route-017",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 516,
  },
  {
    id: "route-018",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 500,
  },
  {
    id: "route-019",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 501,
  },
  {
    id: "route-020",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 502,
  },
  {
    id: "route-021",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 503,
  },
  {
    id: "route-022",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 504,
  },
  {
    id: "route-023",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 505,
  },
  {
    id: "route-024",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 506,
  },
  {
    id: "route-025",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 507,
  },
  {
    id: "route-026",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 508,
  },
  {
    id: "route-027",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 509,
  },
  {
    id: "route-028",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 510,
  },
  {
    id: "route-029",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 511,
  },
  {
    id: "route-030",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 512,
  },
  {
    id: "route-031",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 513,
  },
  {
    id: "route-032",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 514,
  },
  {
    id: "route-033",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 515,
  },
  {
    id: "route-034",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 516,
  },
  {
    id: "route-035",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 500,
  },
  {
    id: "route-036",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 501,
  },
  {
    id: "route-037",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 502,
  },
  {
    id: "route-038",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 503,
  },
  {
    id: "route-039",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 504,
  },
  {
    id: "route-040",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 505,
  },
  {
    id: "route-041",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 506,
  },
  {
    id: "route-042",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 507,
  },
  {
    id: "route-043",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 508,
  },
  {
    id: "route-044",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 509,
  },
  {
    id: "route-045",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 510,
  },
  {
    id: "route-046",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 511,
  },
  {
    id: "route-047",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 512,
  },
  {
    id: "route-048",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 513,
  },
  {
    id: "route-049",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 514,
  },
  {
    id: "route-050",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 515,
  },
  {
    id: "route-051",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 516,
  },
  {
    id: "route-052",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 500,
  },
  {
    id: "route-053",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 501,
  },
  {
    id: "route-054",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 502,
  },
  {
    id: "route-055",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 503,
  },
  {
    id: "route-056",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 504,
  },
  {
    id: "route-057",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 505,
  },
  {
    id: "route-058",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 506,
  },
  {
    id: "route-059",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 507,
  },
  {
    id: "route-060",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 508,
  },
  {
    id: "route-061",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 509,
  },
  {
    id: "route-062",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 510,
  },
  {
    id: "route-063",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 511,
  },
  {
    id: "route-064",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 512,
  },
  {
    id: "route-065",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 513,
  },
  {
    id: "route-066",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 514,
  },
  {
    id: "route-067",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 515,
  },
  {
    id: "route-068",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 516,
  },
  {
    id: "route-069",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 500,
  },
  {
    id: "route-070",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 501,
  },
  {
    id: "route-071",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 502,
  },
  {
    id: "route-072",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 503,
  },
  {
    id: "route-073",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 504,
  },
  {
    id: "route-074",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 505,
  },
  {
    id: "route-075",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 506,
  },
  {
    id: "route-076",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 507,
  },
  {
    id: "route-077",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 508,
  },
  {
    id: "route-078",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 509,
  },
  {
    id: "route-079",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 510,
  },
  {
    id: "route-080",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 511,
  },
  {
    id: "route-081",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 512,
  },
  {
    id: "route-082",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 513,
  },
  {
    id: "route-083",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 514,
  },
  {
    id: "route-084",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 515,
  },
  {
    id: "route-085",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 516,
  },
  {
    id: "route-086",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 500,
  },
  {
    id: "route-087",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 501,
  },
  {
    id: "route-088",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 502,
  },
  {
    id: "route-089",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 503,
  },
  {
    id: "route-090",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 504,
  },
  {
    id: "route-091",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 505,
  },
  {
    id: "route-092",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 506,
  },
  {
    id: "route-093",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 507,
  },
  {
    id: "route-094",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 508,
  },
  {
    id: "route-095",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 509,
  },
  {
    id: "route-096",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 510,
  },
  {
    id: "route-097",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 511,
  },
  {
    id: "route-098",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 512,
  },
  {
    id: "route-099",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 513,
  },
  {
    id: "route-100",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 514,
  },
  {
    id: "route-101",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 515,
  },
  {
    id: "route-102",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 516,
  },
  {
    id: "route-103",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 500,
  },
  {
    id: "route-104",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 501,
  },
  {
    id: "route-105",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 502,
  },
  {
    id: "route-106",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 503,
  },
  {
    id: "route-107",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 504,
  },
  {
    id: "route-108",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 505,
  },
  {
    id: "route-109",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "read",
    priority: 506,
  },
  {
    id: "route-110",
    domain: "skill",
    owner: "typescript-skill",
    operation: "execute",
    priority: 507,
  },
  {
    id: "route-111",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "write",
    priority: 508,
  },
  {
    id: "route-112",
    domain: "command",
    owner: "typescript-command",
    operation: "control",
    priority: 509,
  },
  {
    id: "route-113",
    domain: "agent",
    owner: "typescript-agent",
    operation: "read",
    priority: 510,
  },
  {
    id: "route-114",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "execute",
    priority: 511,
  },
  {
    id: "route-115",
    domain: "mcp",
    owner: "typescript-mcp",
    operation: "write",
    priority: 512,
  },
  {
    id: "route-116",
    domain: "skill",
    owner: "typescript-skill",
    operation: "control",
    priority: 513,
  },
  {
    id: "route-117",
    domain: "plugin",
    owner: "typescript-plugin",
    operation: "read",
    priority: 514,
  },
  {
    id: "route-118",
    domain: "command",
    owner: "typescript-command",
    operation: "execute",
    priority: 515,
  },
  {
    id: "route-119",
    domain: "agent",
    owner: "typescript-agent",
    operation: "write",
    priority: 516,
  },
  {
    id: "route-120",
    domain: "control",
    owner: "typescript-e02-control",
    operation: "control",
    priority: 500,
  },
  // __ROUTE_CASES__
];

function spec(value: RouteCase): ToolSpecContract {
  return {
    name: `matrix_tool_${value.id}`,
    purpose: `route behavior ${value.id}`,
    source: "e02-route-matrix",
    input_schema: { type: "object", properties: { value: { type: "integer" } } },
    output_schema: { type: "object" },
    metadata: { operation: value.operation, version: value.id },
  };
}

for (const value of cases) {
  test(`route matrix ${value.id} selects, binds, consumes, snapshots, and rejects replay`, () => {
      const routes = new E02RouteRuntime({ runtime });
      const revision = routes.reconcile([{
        spec: spec(value),
        domain: value.domain,
        owner: value.owner,
        sourceId: `source-${value.id}`,
        sourceRevision: value.id,
        priority: value.priority,
        metadata: { scenario_id: value.id },
      }]);
      assert.equal(revision?.revision, 1);
      assert.equal(routes.owner(spec(value).name), value.owner);
      assert.equal(routes.domain(spec(value).name), value.domain);
      assert.equal(routes.spec(spec(value).name).metadata.operation, value.operation);
      const argumentsDigest = `sha256:${value.id}`;
      const lease = routes.issueLease({
        toolName: spec(value).name,
        toolCallId: `call-${value.id}`,
        argumentsDigest,
      });
      const consumed = routes.consumeLease(lease.leaseId, {
        toolName: spec(value).name,
        toolCallId: `call-${value.id}`,
        argumentsDigest,
      });
      assert.equal(consumed.owner, value.owner);
      assert.ok(consumed.consumedAt);
      assert.throws(() => routes.consumeLease(lease.leaseId, {
        toolName: spec(value).name,
        toolCallId: `call-${value.id}`,
        argumentsDigest,
      }), /consumed/);
      assert.equal(routes.snapshot().decisions.length, 1);
      assert.equal(routes.health().python_route_fallback, false);
  });
}
